### ISSUE TITLE
when streaming this show log  javax.net.ssl.SSLException: Write error: ssl=0x75a012db08: I/O error during system call, Broken pipe 

### ISSUE THREAD

**Issue by PongPloy2016** [pedroSG94/RootEncoder#1075]
When you press streaming for a moment and for a while it stops and shows.   this unit  show message  log  javax.net.ssl.SSLException: Write error: ssl=0x75a012db08: I/O error during system call, Broken pipe  

and you watch  video demo  in link https://drive.google.com/file/d/1F2j3hjQulBL4rXLpPvA_su5sfj_JT5b-/view?usp=sharing

<img width="1347" alt="Screen Shot 2565-03-25 at 00 50 21" src="https://user-images.githubusercontent.com/8625469/159995996-c163b1e7-0aa6-4cbb-87e9-a524428b3a4a.png">

` javax.net.ssl.SSLException: Write error: ssl=0x7588115008: I/O error during system call, Broken pipe
        at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
        at com.android.org.conscrypt.NativeSsl.write(NativeSsl.java:422)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLOutputStream.write(ConscryptFileDescriptorSocket.java:656)
        at java.io.OutputStream.write(OutputStream.java:75)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLOutputStream.write(ConscryptFileDescriptorSocket.java:629)
        at com.pedro.rtmp.rtmp.message.RtmpHeader.writeHeader(RtmpHeader.kt:121)
        at com.pedro.rtmp.rtmp.message.RtmpHeader.writeHeader(RtmpHeader.kt:112)
        at com.pedro.rtmp.rtmp.message.RtmpMessage.writeHeader(RtmpMessage.kt:118)
        at com.pedro.rtmp.rtmp.CommandsManager.sendAudioPacket(CommandsManager.kt:265)
        at com.pedro.rtmp.rtmp.RtmpSender.start$lambda-2(RtmpSender.kt:123)
        at com.pedro.rtmp.rtmp.RtmpSender.$r8$lambda$RWpSSbIll9sp_byGoOkFIfDGBxg(Unknown Source:0)
        at com.pedro.rtmp.rtmp.RtmpSender$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)`

plase help :

**Comment by pedroSG94** [comment]
Hello,

This is normally produced because the server side close connection abruptly.
You should check server logs to know reason.
Also, you should check internet connection (if you lose connection for a bit this error could be produced).
