### ISSUE TITLE
android.hardware.camera2.CameraAccessException: CAMERA_IN_USE (4): setTorchMode:1491: Torch for camera "0" is not available due to an existing camera user

### ISSUE THREAD

**Issue by saddamsolnkey** [pedroSG94/RootEncoder#1126]
My code : 
    @RequiresApi(Build.VERSION_CODES.M)
    private fun turnOnFlash() {
        try {
            val camManager = getSystemService(Context.CAMERA_SERVICE) as CameraManager
            var cameraId: String? = null
            try {
                cameraId = camManager.cameraIdList[0]
                camManager.setTorchMode(cameraId, true) //Turn ON
            } catch (e: Exception) {
                e.printStackTrace()
                Log.e(TAG,e.message.toString())
            }

        } catch (e: Exception) {
            e.printStackTrace()
        }
    }

2022-05-31 14:16:51.812 23138-23138/com.eye11 W/System.err:     at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:658)
2022-05-31 14:16:51.812 23138-23138/com.eye11 W/System.err:     at android.hardware.camera2.CameraManager$CameraManagerGlobal.setTorchMode(CameraManager.java:878)
2022-05-31 14:16:51.812 23138-23138/com.eye11 W/System.err:     at android.hardware.camera2.CameraManager.setTorchMode(CameraManager.java:519)
2022-05-31 14:16:51.813 23138-23138/com.eye11 W/System.err:     at com.eye11.ui.home.activity.BroadcastActivity.turnOnlashNew(BroadcastActivity.kt:342)
2022-05-31 14:16:51.813 23138-23138/com.eye11 W/System.err:     at com.eye11.ui.home.activity.BroadcastActivity.onCreate$lambda-7(BroadcastActivity.kt:160)
2022-05-31 14:16:51.813 23138-23138/com.eye11 W/System.err:     at com.eye11.ui.home.activity.BroadcastActivity.$r8$lambda$Kxlst-qbeNhfCP3u0yxB7Rw99pQ(Unknown Source:0)
2022-05-31 14:16:51.813 23138-23138/com.eye11 W/System.err:     at com.eye11.ui.home.activity.BroadcastActivity$$ExternalSyntheticLambda13.onClick(Unknown Source:2)
2022-05-31 14:16:51.813 23138-23138/com.eye11 W/System.err:     at android.view.View.performClick(View.java:6314)
2022-05-31 14:16:51.813 23138-23138/com.eye11 W/System.err:     at android.view.View$PerformClick.run(View.java:24793)
2022-05-31 14:16:51.813 23138-23138/com.eye11 W/System.err:     at android.os.Handler.handleCallback(Handler.java:790)
2022-05-31 14:16:51.813 23138-23138/com.eye11 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2022-05-31 14:16:51.814 23138-23138/com.eye11 W/System.err:     at android.os.Looper.loop(Looper.java:164)
2022-05-31 14:16:51.814 23138-23138/com.eye11 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6543)
2022-05-31 14:16:51.814 23138-23138/com.eye11 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-05-31 14:16:51.814 23138-23138/com.eye11 W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
2022-05-31 14:16:51.814 23138-23138/com.eye11 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
2022-05-31 14:16:51.815 23138-23138/com.eye11 W/System.err: Caused by: android.os.ServiceSpecificException: setTorchMode:1491: Torch for camera "0" is not available due to an existing camera user (code 7)
2022-05-31 14:16:51.815 23138-23138/com.eye11 W/System.err:     at android.os.Parcel.readException(Parcel.java:2027)
2022-05-31 14:16:51.815 23138-23138/com.eye11 W/System.err:     at android.os.Parcel.readException(Parcel.java:1959)
2022-05-31 14:16:51.815 23138-23138/com.eye11 W/System.err:     at android.hardware.ICameraService$Stub$Proxy.setTorchMode(ICameraService.java:547)
2022-05-31 14:16:51.816 23138-23138/com.eye11 W/System.err:     at android.hardware.camera2.CameraManager$CameraManagerGlobal.setTorchMode(CameraManager.java:876)
2022-05-31 14:16:51.816 23138-23138/com.eye11 W/System.err: 	... 14 more

2022-05-31 14:16:51.816 23138-23138/com.eye11 E/MuxLive: CAMERA_IN_USE (4): setTorchMode:1491: Torch for camera "0" is not available due to an existing camera user

**Comment by pedroSG94** [comment]
Hello,

I dont understand your question. You are not using my library so I can't help you so much. I only can tell you make sure that you have access to camera (available and not in use)
