### ISSUE TITLE
Cannot add frame, queue is full

### ISSUE THREAD

**Issue by Elswah** [pedroSG94/RootEncoder#1146]
Cannot add frame, queue is full
2022-06-28 09:03:39.722 23090-25238/com.alexvas.rtsp.demo W/System.err: java.net.SocketTimeoutException: Read timed out
2022-06-28 09:03:39.722 23090-25238/com.alexvas.rtsp.demo W/System.err:     at java.net.SocketInputStream.socketRead0(Native Method)
2022-06-28 09:03:39.723 23090-25238/com.alexvas.rtsp.demo W/System.err:     at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
2022-06-28 09:03:39.723 23090-25238/com.alexvas.rtsp.demo W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:176)
2022-06-28 09:03:39.723 23090-25238/com.alexvas.rtsp.demo W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:144)
2022-06-28 09:03:39.723 23090-25238/com.alexvas.rtsp.demo W/System.err:     at com.alexvas.utils.NetUtils.readData(NetUtils.java:229)
2022-06-28 09:03:39.723 23090-25238/com.alexvas.rtsp.demo W/System.err:     at com.alexvas.rtsp.RtspClient.readRtpData(RtspClient.java:604)
2022-06-28 09:03:39.724 23090-25238/com.alexvas.rtsp.demo W/System.err:     at com.alexvas.rtsp.RtspClient.execute(RtspClient.java:501)
2022-06-28 09:03:39.724 23090-25238/com.alexvas.rtsp.demo W/System.err:     at com.alexvas.rtsp.widget.RtspSurfaceView$RtspThread.run(RtspSurfaceView.kt:228)

**Comment by pedroSG94** [comment]
Hello,

I can't help you with this info. You need to know that:

- I don't know any context about the crash/problem to reproduce or get an idea about the case.
- In your error the package is not my package and all crash lines are not in my code. Your code is obviusly modified.
- If you have problems with my code modified. I need to tell you that I can't give you full support for it (maintain modifications are you own responsability obviously) but I can try give you hints about the problem if you explain me the objetive and share me code changes if necessary
