### ISSUE TITLE
ANR happens during screen casting -> com.pedro.encoder.input.gl.render.ScreenRender.draw

### ISSUE THREAD

**Issue by ahulyk** [pedroSG94/RootEncoder#1213]
That is hard to reproduce, but it happens from time to time:

`ScreenRender.java line 137 com.pedro.encoder.input.gl.render.ScreenRender.draw`

```
Thread-4 (native) tid=27 systid=5918 Root blocking:

#00 pc 0xddb44 libc.so (__ioctl + 4)
#01 pc 0x97108 libc.so (ioctl + 156)
#02 pc 0x86ccc libhidlbase.so (android::hardware::IPCThreadState::talkWithDriver(bool) + 216)
#03 pc 0x88b5c libhidlbase.so (android::hardware::IPCThreadState::waitForResponse(android::hardware::Parcel*, int*) + 48)
#04 pc 0x886ac libhidlbase.so (android::hardware::IPCThreadState::transact(int, unsigned int, android::hardware::Parcel const&, android::hardware::Parcel*, unsigned int) + 116)
#05 pc 0x83fbc libhidlbase.so (android::hardware::BpHwBinder::transact(unsigned int, android::hardware::Parcel const&, android::hardware::Parcel*, unsigned int, std::__1::function<void (android::hardware::Parcel&)>) + 76)
#06 pc 0x2f204 android.hardware.graphics.bufferqueue@1.0.so (android::hardware::graphics::bufferqueue::V1_0::BpHwGraphicBufferProducer::_hidl_dequeueBuffer(android::hardware::IInterface*, android::hardware::details::HidlInstrumentor*, unsigned int, unsigned int, android::hardware::graphics::common::V1_0::PixelFormat, unsigned int, bool, std::__1::function<void (int, int, android::hardware::hidl_handle const&, android::hardware::graphics::bufferqueue::V1_0::IGraphicBufferProducer::FrameEventHistoryDelta const&)>) (.cfi) + 456)
#07 pc 0x29d34 android.hardware.graphics.bufferqueue@1.0.so (android::hardware::graphics::bufferqueue::V1_0::BpHwGraphicBufferProducer::dequeueBuffer(unsigned int, unsigned int, android::hardware::graphics::common::V1_0::PixelFormat, unsigned int, bool, std::__1::function<void (int, int, android::hardware::hidl_handle const&, android::hardware::graphics::bufferqueue::V1_0::IGraphicBufferProducer::FrameEventHistoryDelta const&)>) + 192)
#08 pc 0xd56b0 libgui.so (android::hardware::graphics::bufferqueue::V1_0::utils::H2BGraphicBufferProducer::dequeueBuffer(int*, android::sp<android::Fence>*, unsigned int, unsigned int, int, unsigned long, unsigned long*, android::FrameEventHistoryDelta*) + 208)
#09 pc 0xbbb30 libgui.so (android::Surface::dequeueBuffer(ANativeWindowBuffer**, int*) + 396)
#10 pc 0xf464 eglSubDriverAndroid.so 
#11 pc 0xe6cc eglSubDriverAndroid.so 
#12 pc 0x25d77c libGLESv2_adreno.so (!!!0000!c441fda5cce3b6ed49be7fa818989c!02e24b95a5! + 148)
#13 pc 0x168f10 libGLESv2_adreno.so (!!!0000!c290b97fcf9059e9ebe30800178359!02e24b95a5! + 336)
#14 pc 0x16a9d4 libGLESv2_adreno.so (!!!0000!788a94b791f481718be1df9bbb4860!02e24b95a5! + 2956)
#15 pc 0x1aace4 libGLESv2_adreno.so (!!!0000!73616227b17af30cf97cb6b1578c04!02e24b95a5! + 132)
       at android.opengl.GLES20.glClear(GLES20.java)
       at com.pedro.encoder.input.gl.render.ScreenRender.draw(ScreenRender.java:137)
       at com.pedro.encoder.input.gl.render.ScreenRender.draw(ScreenRender.java:102)
       at com.pedro.encoder.input.gl.render.ManagerRender.drawScreen(ManagerRender.java:76)
       at com.pedro.rtplibrary.view.OffScreenGlThread.run(OffScreenGlThread.java:301)
       at java.lang.Thread.run(Thread.java:923)
```

```
main (blocked) tid=1 systid=23760 | waiting to lock <0x0ecbf4cd> (java.lang.Object) held by thread 27

       at com.pedro.rtplibrary.view.OffScreenGlThread.onFrameAvailable(OffScreenGlThread.java:328)
       at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:211)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:247)
       at android.app.ActivityThread.main(ActivityThread.java:8676)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by pedroSG94** [comment]
Which device are you using? (model and Android version)

**Comment by ahulyk** [comment]
> com.pedro.encoder.input.gl.render.ScreenRender.draw

Galaxy Tab A7 -> Android 11
XiaoXin Pad -> Android 11

**Comment by T-ONLY** [comment]
Can you tell me how to solve this problem

**Comment by pedroSG94** [comment]
Hello,

Which library version are you using?
This error could be solved in the last library version

**Comment by pedroSG94** [comment]
Closing as duplicated:
https://github.com/pedroSG94/RootEncoder/issues/1421
