### ISSUE TITLE
tapToFocus(event) - rect.left must be nonnegative

### ISSUE THREAD

**Issue by alexz006** [pedroSG94/RootEncoder#1270]
my MainActivity:
```java
    @Override
    public boolean onTouchEvent(MotionEvent event) {
        if (camera2 != null && event.getAction() == MotionEvent.ACTION_DOWN && openGlView.getVisibility() != View.GONE) {
            camera2.tapToFocus(event);
        }
        return super.onTouchEvent(event);
    }
```

Camera2ApiManager:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/f1d2fc6fba5ebba98e2be6bb5360d81103106816/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java#L549
```java
public void tapToFocus(MotionEvent event) {
...
    Rect touchRect = new Rect((int) (x - 100), (int) (y - 100),
        (int) (x + 100), (int) (y + 100));
...
```

Error:
```
java.lang.IllegalArgumentException: rect.left must be nonnegative
 at com.android.internal.util.Preconditions.checkArgumentNonnegative(Unknown Source:5)
 at android.hardware.camera2.params.MeteringRectangle.<init>(Unknown Source:14)
 at com.pedro.encoder.input.video.Camera2ApiManager.tapToFocus(Camera2ApiManager.java:551)
 at com.pedro.rtplibrary.base.Camera2Base.tapToFocus(Camera2Base.java:954)
```

Working Solution
my MainActivity:
```java
    @Override
    public boolean onTouchEvent(MotionEvent event) {
        if (camera2 != null && event.getAction() == MotionEvent.ACTION_DOWN && openGlView.getVisibility() != View.GONE
            && event.getX() >= 100 && event.getY() >= 100) {
            camera2.tapToFocus(event); 
        }
        return super.onTouchEvent(event);
    }
```

**Comment by pedroSG94** [comment]
Hello,

This issue is now fixed:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/a3ecf8ef9dbd5a494afccfb0ac9b401153d252f4

You can compile this gradle with the commit:
```gradle
	        implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:a3ecf8ef9d'
```
Or wait for next release version. Keep in mind that next version could take time to release because I want add SRT protocol and I want to get a version more or less stable to use.
