### ISSUE TITLE
App running on Android 11 and Library 2.2.7+ Crashes (NPE) at  rtmpCamera1.startStream();

### ISSUE THREAD

**Issue by AlexUrrutia** [pedroSG94/RootEncoder#1284]
**Describe the bug**
App crashes when starting live stream

**To Reproduce**
1. Setup a new emulator using **Android 11**
2. start a live stream using  `rtmpCamera1.startStream();`
3. App crashes

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaCodec.start()' on a null object reference
       at com.pedro.encoder.BaseEncoder.initCodec(BaseEncoder.java:79)
       at com.pedro.encoder.BaseEncoder.start(BaseEncoder.java:65)
       at com.pedro.library.base.Camera1Base.startEncoders(Camera1Base.java:700)
       at com.pedro.library.base.Camera1Base.startStream(Camera1Base.java:691)
       at com.myapp.activity.MainActivity$26.run(MainActivity.java:1393)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

**Smartphone (please complete the following information):**
 - Library: **2.2.8**
 - Device: Pixel, Samsung, Motorola
 - OS: **Android 11**
 - RtmpCamera1

**Comment by AlexUrrutia** [comment]
Solved, was using incorrect params on `prepareVideo();`
