### ISSUE TITLE
AudioDecoder Decoding error

### ISSUE THREAD

**Issue by Munccccc** [pedroSG94/RootEncoder#1289]
2023-09-28 15:52:26.437 25126-25126 AudioDecoder            com.pedro.rtpstreamer                I  default input size
2023-09-28 15:52:26.438 25126-25126 AudioEncoder            com.pedro.rtpstreamer                I  2 encoders found
2023-09-28 15:52:26.439 25126-25126 AudioEncoder            com.pedro.rtpstreamer                I  Encoder selected c2.android.aac.encoder
2023-09-28 15:52:26.448 25126-6517  CCodecConfig            com.pedro.rtpstreamer                D  read media type: audio/mp4a-latm
2023-09-28 15:52:26.454 25126-6517  CCodecConfig            com.pedro.rtpstreamer                D  c2 config is Dict {
                                                                                                      c2::u32 coded.bitrate.value = 64000
                                                                                                      c2::u32 coded.pl.level = 0
                                                                                                      c2::u32 coded.pl.profile = 8192
                                                                                                      c2::u32 coding.aac-sbr-mode.value = 3
                                                                                                      c2::u32 input.buffers.max-size.value = 2048
                                                                                                      c2::u32 input.delay.value = 0
                                                                                                      string input.media-type.value = "audio/raw"
                                                                                                      string output.media-type.value = "audio/mp4a-latm"
                                                                                                      c2::u32 raw.channel-count.value = 1
                                                                                                      c2::u32 raw.sample-rate.value = 44100
                                                                                                    }
2023-09-28 15:52:26.459 25126-6517  CCodecConfig            com.pedro.rtpstreamer                D  c2 config is Dict {
                                                                                                      c2::u32 coded.bitrate.value = 65536
                                                                                                      c2::u32 coded.pl.level = 0
                                                                                                      c2::u32 coded.pl.profile = 8192
                                                                                                      c2::u32 coding.aac-sbr-mode.value = 3
                                                                                                      c2::u32 input.buffers.max-size.value = 2048
                                                                                                      c2::u32 input.delay.value = 0
                                                                                                      string input.media-type.value = "audio/raw"
                                                                                                      string output.media-type.value = "audio/mp4a-latm"
                                                                                                      c2::u32 raw.channel-count.value = 1
                                                                                                      c2::u32 raw.sample-rate.value = 44100
                                                                                                    }
2023-09-28 15:52:26.461 25126-6517  CCodec                  com.pedro.rtpstreamer                D  setup formats input: AMessage(what = 0x00000000) = {
                                                                                                      int32_t channel-count = 1
                                                                                                      int32_t max-input-size = 2048
                                                                                                      string mime = "audio/raw"
                                                                                                      int32_t sample-rate = 44100
                                                                                                    } and output: AMessage(what = 0x00000000) = {
                                                                                                      int32_t bitrate = 65536
                                                                                                      int32_t channel-count = 1
                                                                                                      int32_t level = 0
                                                                                                      int32_t max-bitrate = 65536
                                                                                                      string mime = "audio/mp4a-latm"
                                                                                                      int32_t profile = 2
                                                                                                      int32_t sample-rate = 44100
                                                                                                    }
2023-09-28 15:52:26.461 25126-25126 AudioEncoder            com.pedro.rtpstreamer                I  prepared
2023-09-28 15:52:26.497 25126-25126 AudioEncoder            com.pedro.rtpstreamer                I  started
2023-09-28 15:52:26.534 25126-25126 AudioDecoder            com.pedro.rtpstreamer                I  start decoder
2023-09-28 15:52:26.599 25126-6522  CommandsManager         com.pedro.rtpstreamer                I  send Command(name='connect', transactionId=1, timeStamp=0, streamId=0, data=[AmfString value: connect, AmfNumber value: 1.0, AmfObject properties: {AmfString value: app=AmfString value: live, AmfString value: flashVer=AmfString value: FMLE/3.0 (compatible; Lavf57.56.101), AmfString value: swfUrl=AmfString value: , AmfString value: tcUrl=AmfString value: rtmp://218.17.50.142:7065/live, AmfString value: fpad=AmfBoolean value: false, AmfString value: capabilities=AmfNumber value: 239.0, AmfString value: audioCodecs=AmfNumber value: 3191.0, AmfString value: videoCodecs=AmfNumber value: 252.0, AmfString value: videoFunction=AmfNumber value: 1.0, AmfString value: pageUrl=AmfString value: , AmfString value: objectEncoding=AmfNumber value: 0.0}], bodySize=271)
2023-09-28 15:52:26.618 25126-6521  AudioDecoder            com.pedro.rtpstreamer                I  Decoding error
                                                                                                    java.lang.IllegalStateException: buffer is inaccessible
                                                                                                    	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:231)
                                                                                                    	at com.pedro.encoder.input.decoder.AudioDecoder.decodeOutput(AudioDecoder.java:98)
                                                                                                    	at com.pedro.encoder.input.decoder.BaseDecoder.decode(BaseDecoder.java:249)
                                                                                                    	at com.pedro.encoder.input.decoder.BaseDecoder.lambda$start$0$com-pedro-encoder-input-decoder-BaseDecoder(BaseDecoder.java:111)
                                                                                                    	at com.pedro.encoder.input.decoder.BaseDecoder$$ExternalSyntheticLambda0.run(Unknown Source:2)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:883)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
2023-09-28 15:52:26.777 25126-6522  CommandsManager         com.pedro.rtpstreamer                I  send Data(name='@setDataFrame', data=[AmfString value: onMetaData, AmfEcmaArray length: 12, properties: {AmfString value: duration=AmfNumber value: 0.0, AmfString value: width=AmfNumber value: 1920.0, AmfString value: height=AmfNumber value: 1080.0, AmfString value: videocodecid=AmfNumber value: 7.0, AmfString value: framerate=AmfNumber value: 29.0, AmfString value: videodatarate=AmfNumber value: 0.0, AmfString value: audiocodecid=AmfNumber value: 10.0, AmfString value: audiosamplerate=AmfNumber value: 44100.0, AmfString value: audiosamplesize=AmfNumber value: 16.0, AmfString value: audiodatarate=AmfNumber value: 0.0, AmfString value: stereo=AmfBoolean value: false, AmfString value: filesize=AmfNumber value: 0.0}], bodySize=284)
2023-09-28 15:53:26.943 25126-25126 AudioDecoder            com.pedro.rtpstreamer                I  stop decoder
2023-09-28 15:53:26.982 25126-25126 AudioEncoder            com.pedro.rtpstreamer                I  stopped

**Comment by pedroSG94** [comment]
Hello,

Are you using the last library version? The line crash is not the same that in code. can you tell me line that fail?
Also, let me know info about your device. Model, android version, etc

**Comment by pedroSG94** [comment]
I did a branch for this case and pushed a commit that could solve the problem:
https://github.com/pedroSG94/RootEncoder/tree/fix-decode-illegalstate
Test this branch and let me know if the problem is solved or the problem persist

**Comment by Munccccc** [comment]
> I did a branch for this case and pushed a commit that could solve the problem: https://github.com/pedroSG94/RootEncoder/tree/fix-decode-illegalstate Test this branch and let me know if the problem is solved or the problem persist

Hi，
Android10 arm64 
The real-time push flow is normal, but the file push flow will be abnormal. I have tried other pixel phones and it is normal, maybe it is the problem of this device.I will try this branch

**Comment by Munccccc** [comment]
This branch audio can be decoded normally, I used 2.2.4 before, thank you
