### ISSUE TITLE
clearFilters() will cause crash due to non-nullable type

### ISSUE THREAD

**Issue by kenle** [pedroSG94/RootEncoder#1422]
Hi @pedroSG94 , my program was crashing when using clearFilters() and I believe I found a bug due to Kotlin and null "safety" features.

https://github.com/pedroSG94/RootEncoder/blob/a4ab764acc90f5b54161700bc76aef65eae144a3/encoder/src/main/java/com/pedro/encoder/input/gl/render/MainRender.kt#L143

### 1) In MainRender.kt, baseFilterRender is declared non-nullable
```
fun setFilterAction(filterAction: FilterAction?, position: Int, baseFilterRender: BaseFilterRender) {
```

### 2) In GlStreamInterface.kt and OpenGlView.java clearFilters() will set filter position 0 to null
``` 
  override fun clearFilters() {
    filterQueue.add(Filter(FilterAction.CLEAR, 0, null))
  }
```
This will set baseFilterRender to null within the Filter instance

### 3) In GlStreamInterface.kt and OpenGlView.java draw() functions when it reaches the following line that calls mainRender.setFilterAction it will crash since baseFilterRender is null, and the field is non-nullable
```
if (!filterQueue.isEmpty() && mainRender.isReady) {
      try {
        val filter = filterQueue.take()
        mainRender.setFilterAction(filter.filterAction, filter.position, filter.baseFilterRender)
      } catch (e: InterruptedException) {
        Thread.currentThread().interrupt()
      }
}
```
### Log Message
```
E/AndroidRuntime(10351): java.lang.NullPointerException: getBaseFilterRender(...) must not be null
E/AndroidRuntime(10351):        at com.pedro.library.view.GlStreamInterface.draw(GlStreamInterface.kt:165)
E/AndroidRuntime(10351):        at com.pedro.library.view.GlStreamInterface.onFrameAvailable$lambda$0(GlStreamInterface.kt:208)
E/AndroidRuntime(10351):        at com.pedro.library.view.GlStreamInterface.$r8$lambda$F3uPVoonfZHixlk2XWkWc7gH68U(Unknown Source:0)
E/AndroidRuntime(10351):        at com.pedro.library.view.GlStreamInterface$$ExternalSyntheticLambda0.run(Unknown Source:2)
E/AndroidRuntime(10351):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/AndroidRuntime(10351):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/AndroidRuntime(10351):        at java.lang.Thread.run(Thread.java:1012)
```

### The Possible Fix
In MainRender.kt, set baseFilterRender to be nullable
```
fun setFilterAction(filterAction: FilterAction?, position: Int, baseFilterRender: BaseFilterRender?) {
```

And this is why I'm not the biggest fan of some of these new null-safety languages.  They allow you to compile that code, but during run-time it will crash due to type mismatch.

**Comment by pedroSG94** [comment]
Hello,

Thank you for the report. Fixed here:
https://github.com/pedroSG94/RootEncoder/commit/0459e74e85c9e199074faa21f48b948d4b1dde06#diff-6efae85175ec84932391ca387cfe4ec3e708b70dac3c36613daac656c4b561ea
You can use it with this gradle while I upload a new version:
```gradle
  implementation 'com.github.pedroSG94.RootEncoder:library:0459e74e85'
``

**Comment by kenle** [comment]
Thank you @pedroSG94

**Comment by pedroSG94** [comment]
Closing as fixed
