### ISSUE TITLE
Android - RTSP Streaming over public ip address

### ISSUE THREAD

**Issue by tomdomnicone** [pedroSG94/RootEncoder#1442]
**Describe the bug**
I want to stream from my android device over my public ip address, that can be viewed by anyone with the respective rtsp url that is being built by the public ip address.
Connecting with public ip address

**To Reproduce**
- Run the application
- Click on Screen
- Enter your public ip address to build the rtsp url
- Click on icon to connect with the server
- Connection broke

**Expected behavior**
Connection should be established and stream should be started on public ip.

Crash/Error logs:
`connection error
                                                                                                    java.net.SocketTimeoutException: failed to connect to /ACTUAL_IP_VALUE (port 19302) from /192.0.0.4 (port 33460) after 5000ms
                                                                                                    	at libcore.io.IoBridge.connectErrno(IoBridge.java:235)
                                                                                                    	at libcore.io.IoBridge.connect(IoBridge.java:179)
                                                                                                    	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
                                                                                                    	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
                                                                                                    	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
                                                                                                    	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
                                                                                                    	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
                                                                                                    	at java.net.Socket.connect(Socket.java:646)
                                                                                                    	at com.pedro.rtsp.rtsp.RtspClient$connect$1.invokeSuspend(RtspClient.kt:244)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
                                                                                                    	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684) `

**Smartphone (please complete the following information):**
- Compiled the root project from this git repo's master branch only.

**Additional Note**
Is it even possible to achieve with this library?

**Comment by pedroSG94** [comment]
Hello,

Are you trying to connect to a RTSP url and reproduce the stream content or send data (video/audio) to that RTSP url?

If you want reproduce stream content. It is not your library.
As you can see in the library description in readme it is a library to push data to a media server not to reproduce data from a media server. You can use ExoPlayer for this case.

If you want to do the second case. You can do it and this error means that you can't connect to that server so you have a porblem in the network to access to that server

**Comment by tomdomnicone** [comment]
Hi @pedroSG94,

Thanks for the revert.

I want to have the functionality to stream camera over the RTSP on my public IP address, and it can be viewed by anyone with whom I'll share my public IP address using the RTSP URL which is being recommended by this library.

RTSP Stream URL: "rtsp://${ANDROID_DEVICE_PUBLIC_IP_ADDRESS}:${PORT}/streamName/path"


So my app will start the streaming over this URL and that can we viewed remotely with this URL.

**Comment by pedroSG94** [comment]
Hello,

Which media server do you have installed in that address?
Did you test that the server is correctly configured using ffmpeg or OBS?

**Comment by tomdomnicone** [comment]
Hi @pedroSG94, do we required to have a server? I was relying on this library for all the streaming, and want to watch the stream from other end. I don't want to have any server?

Can you please help me with that?

**Comment by pedroSG94** [comment]
Hello,

Yes, you need a server. This server receive the stream from this library and allow others to connect and reproduce the stream.
You have few servers here:
https://github.com/pedroSG94/RootEncoder/wiki/Media-servers-tested#rtsp

Also, you can use others platforms like YouTube or Twitch protocol as server. This platforms only support RTMP and you need an account and configure the stream to work
