### ISSUE TITLE
java.lang.IllegalArgumentException: Unknown message type byte: 1D

### ISSUE THREAD

**Issue by yuessir** [pedroSG94/RootEncoder#1466]
**Describe the bug**
 crash on start streaming
I used the external uvc camera or internal phone's camera to stream, when I started to stream ,and my app was crashed. I have reasons to use the old version, so could you tell me how to fix it?
sample on [repo](https://github.com/yuessir/rtmp-streaming/tree/dev)
exception

```
024-04-28 17:59:34.330  4276-5658  AndroidRuntime          com.imashik.rtmpstream               E  FATAL EXCEPTION: Thread-9
                                                                                                    Process: com.imashik.rtmpstream, PID: 4276
                                                                                                    java.lang.IllegalArgumentException: Unknown message type byte: 1D
                                                                                                    	at com.github.faucamp.simplertmp.packets.RtmpHeader$MessageType.valueOf(RtmpHeader.java:149)
                                                                                                    	at com.github.faucamp.simplertmp.packets.RtmpHeader.readHeaderImpl(RtmpHeader.java:234)
                                                                                                    	at com.github.faucamp.simplertmp.packets.RtmpHeader.readHeader(RtmpHeader.java:213)
                                                                                                    	at com.github.faucamp.simplertmp.io.RtmpDecoder.readPacket(RtmpDecoder.java:36)
                                                                                                    	at com.github.faucamp.simplertmp.io.RtmpConnection.handleRxPacketLoop(RtmpConnection.java:527)
                                                                                                    	at com.github.faucamp.simplertmp.io.RtmpConnection.access$000(RtmpConnection.java:41)
                                                                                                    	at com.github.faucamp.simplertmp.io.RtmpConnection$1.run(RtmpConnection.java:160)
                                                                                                    	at java.lang.Thread.run(Thread.java:764)
```

```

---------------------------- PROCESS ENDED (4276) for package com.imashik.rtmpstream ----------------------------
2024-04-28 17:59:34.546  3852-3897  WindowManager           system_server                        E  RemoteException occurs on reporting focusChanged, w=Window{3fa6fe9 u0 com.imashik.rtmpstream/com.imashik.rtmpstream.MobileCamBroadcastActivity EXITING}
                                                                                                    android.os.DeadObjectException
                                                                                                    	at android.os.BinderProxy.transactNative(Native Method)
                                                                                                    	at android.os.BinderProxy.transact(Binder.java:1145)
                                                                                                    	at android.view.IWindow$Stub$Proxy.windowFocusChanged(IWindow.java:500)
                                                                                                    	at com.android.server.wm.WindowState.reportFocusChangedSerialized(WindowState.java:3951)
                                                                                                    	at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:5507)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:65)
                                                                                                    	at com.android.server.ServiceThread.run(ServiceThread.java:44)
2024-04-28 17:59:34.562  3852-5759  WindowManager           system_server                        E  win=Window{3fa6fe9 u0 com.imashik.rtmpstream/com.imashik.rtmpstream.MobileCamBroadcastActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.AppWindowToken.destroySurfaces:871 com.android.server.wm.AppWindowToken.destroySurfaces:852 com.android.server.wm.WindowState.onExitAnimationDone:5443 com.android.server.wm.-$$Lambda$01bPtngJg5AqEoOWfW3rWfV7MH4.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.AppWindowToken.onAnimationFinished:2413 com.android.server.wm.AppWindowToken.setVisibility:552 
---------------------------- PROCESS STARTED (5735) for package com.imashik.rtmpstream ----------------------------
```

**Smartphone (please complete the following information):**
 - Library version 2.0.2
 - Device: samsung s8
 - OS: android 9
 - Media server [e.g. srs, version 5.0]
 - Class used [e.g. RtmpCamera1]

**Additional context**

detail logs 
[logcat.html.zip](https://github.com/pedroSG94/RootEncoder/files/15141732/logcat.html.zip)

**Comment by pedroSG94** [comment]
Hello,

Library version 2.0.2 is really old. Please update to the last library version and test again.
If you need an external UVC camera you can try with this branch:
https://github.com/pedroSG94/RootEncoder/tree/feature/extra-video-source

**Comment by yuessir** [comment]
ok after migration to v2.3.5, the error was gone. Thanks.
