### ISSUE TITLE
App crashing while migrating to Android 14 from Android 13

### ISSUE THREAD

**Issue by dev-android1** [pedroSG94/RootEncoder#1478]
I was using  'implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:2.1.9’ for streaming screen of my app to RTMP server. It was working fine till Android 13. when we upgraded our app to Android 14 then app started crashing
Logs -
_targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION] any of the permissions allOf=false [android.permission.CAPTURE_VIDEO_OUTPUT, android:project_media]_

After that I tried to upgrade version of library but I found different package name of library 
Earlier - com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:2.1.9
Now --   com.github.pedroSG94.RootEncoder:rtplibrary:2.2.6

Have we changed anything related to classes because we have customized some classes by extending to fulfill our goal. when I switched to new package then I am getting lots of errors like -

com/pedro/rtmp/flv/video/ProfileIop.class) class file has wrong version 61.0, should be 55.0

Please let me know how can I resolve this issue.

**Comment by dev-android1** [comment]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=12223, result=-1, data=Intent { (has extras) }} to activity {com.test.myactivity}: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
                                                                                                    	at android.app.ActivityThread.deliverResults(ActivityThread.java:6062)
                                                                                                    	at android.app.ActivityThread.handleSendResult(ActivityThread.java:6101)
                                                                                                    	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8893)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by pedroSG94** [comment]
Hello,

The error that you reported is not related with the library code. It is a problem in the service implementation. 
In Android 14 you must include permissions to the service in the manifest like here:
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/AndroidManifest.xml#L64
Depend if you are using MediaProjection (capture screen), camera or microphone you need and more:
https://developer.android.com/about/versions/14/changes/fgs-types-required
In case you use all, you need add something like this:
```xml
    <service android:name="com.pedro.streamapp.StreamService"
        android:foregroundServiceType="mediaProjection|camera|microphone"
        />
```


> com/pedro/rtmp/flv/video/ProfileIop.class) class file has wrong version 61.0, should be 55.0

This usually is related with the java version used in the library and in your project. Try to use the same version in both. The library version 2.2.6 use java 17.

I recommend you continue with library version 2.1.9 if it is working fine for you if you don't want update java version.

**Comment by dev-android1** [comment]
Thanks for reply

I have already added this tag in AndroidManifest but error not resolved
 <service android:name=".DisplayService"
            android:foregroundServiceType="mediaProjection" />

**Comment by dev-android1** [comment]
As per my understanding there is some issue with at `com.pedro.rtplibrary.base.DisplayBase.prepareInternalAudio(DisplayBase.java:232)`

**Comment by pedroSG94** [comment]
Are you starting your service with startforeground method?
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/screen/ScreenService.kt#L89

**Comment by dev-android1** [comment]
No

**Comment by dev-android1** [comment]
I was able to solve one issue but got other issue -

caused by: java.lang.IllegalStateException: Must register a callback before starting capture, to manage resources in response to MediaProjection states.

 java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=12223, result=-1, data=Intent { (has extras) }} to activity {com.test.android/com.test.android.activity.RecordActivity}: java.lang.IllegalStateException: Must register a callback before starting capture, to manage resources in response to MediaProjection states.
                 	at android.app.ActivityThread.deliverResults(ActivityThread.java:6062)
                 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:6101)
                 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
                 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
                 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loopOnce(Looper.java:230)
                 	at android.os.Looper.loop(Looper.java:319)
                 	at android.app.ActivityThread.main(ActivityThread.java:8893)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                 Caused by: java.lang.IllegalStateException: Must register a callback before starting capture, to manage resources in response to MediaProjection states.
                 	at android.media.projection.MediaProjection.createVirtualDisplay(MediaProjection.java:214)
                 	at com.pedro.rtplibrary.base.DisplayBase.startEncoders(DisplayBase.java:404)
                 	at com.pedro.rtplibrary.base.DisplayBase.startStream(DisplayBase.java:376)

**Comment by pedroSG94** [comment]
Hello,

Ok, you will need modify DisplayBase to fix it.
Since you can't directly modify DisplayBase you can copy that class and RtmpDisplay class and modify the classes. You only need add a callback to DisplayBase here:
https://github.com/pedroSG94/RootEncoder/blob/2.1.9/rtplibrary/src/main/java/com/pedro/rtplibrary/base/DisplayBase.java#L400
https://github.com/pedroSG94/RootEncoder/blob/2.1.9/rtplibrary/src/main/java/com/pedro/rtplibrary/base/DisplayBase.java#L403
Like here:
https://github.com/pedroSG94/RootEncoder/blob/2.4.4/library/src/main/java/com/pedro/library/base/DisplayBase.java#L424
https://github.com/pedroSG94/RootEncoder/blob/2.4.4/library/src/main/java/com/pedro/library/base/DisplayBase.java#L428

In RtmpDislpay class copied you only need change the class that you extend from DisplayBase original class to the class copied and modified with the callback added

**Comment by dev-android1** [comment]
Thank you @pedroSG94 . I am able to resolve this by using above approach

**Comment by dev-android1** [comment]
Resolved
