### ISSUE TITLE
Hello! I would like to ask you if this library can achieve screen recording and push stream, not through the camera through the screen recording to push the device picture and sound to the server.

### ISSUE THREAD

**Issue by zhouqunhuang** [pedroSG94/RootEncoder#1492]
Hello! I would like to ask you if this library can achieve screen recording and push stream, not through the camera through the screen recording to push the device picture and sound to the server.

**Comment by pedroSG94** [comment]
Hello,

Yes, this is possible. You have an example code here:
https://github.com/pedroSG94/RootEncoder/tree/master/app/src/main/java/com/pedro/streamer/screen

You can compile the app example and test it

**Comment by zhouqunhuang** [comment]
Hello! What is the maximum resolution you support?!

**Comment by pedroSG94** [comment]
I support all resolutions. The max resolution depend of your device. You have 2 limitations:
- Resolution supported by your source (camera, screen, etc):
In this case the resolution is your device screen resolution. The library allow you scale it as you want but remember that, increase the resolution above of the original resolution, produce a pixelation.
- Resolution supported by your encoder:
Your device has video encoders that are used to stream. Depend of that encoders you can use a better resolution.

**Comment by pedroSG94** [comment]
I don't understand your image but you can use AudioInternalSource or MicrophoneSource depend of your needs

**Comment by zhouqunhuang** [comment]
I see that your project uses MicrophoneSource(). How to write if you use AudioInternalSource, or I want to use both.

**Comment by zhouqunhuang** [comment]
I see that your project uses MicrophoneSource(). How to write if you use AudioInternalSource, or I want to use both.
` genericStream =
            GenericStream(baseContext, this, NoVideoSource(), MicrophoneSource()).apply {
                //This is important to keep a constant fps because media projection only produce fps if the screen change
                getGlInterface().setForceRender(true, 15)
            }`

**Comment by pedroSG94** [comment]
Hello,

If you use AudioInternalSource you can follow Screen example and add AudioInternalSource here:
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/screen/ScreenService.kt#L141
exactly the same that ScreenSource you can create an InternalAudioSource and set to stream using changeAudioSource

**Comment by zhouqunhuang** [comment]
Sorry, I don't know how to write. Can you add an audio selection feature? Add a source selection to the screen recording, similar to the image I gave you above. Can you help me?! Thank you!

**Comment by zhouqunhuang** [comment]
Hello! Can you implement this feature? I really need this feature because when I'm recording a video that's playing on my device and I push it to the server there's no video sound. There is also a problem, I am playing video in the player and when I record and push to the server, no video screen is black. What is the cause of this.

**Comment by pedroSG94** [comment]
Hello,

You have a code example about how to change the AudioSource in the link referred above. Also, you can check this code if you want more examples:
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/rotation/RotationActivity.kt#L92
This case change the audioSource to a MicrophoneSource, if you want change to InternalAudioSource the code is exactly the same.

Create a Modal like you shared is not related with the library, you should develop it yourself.

**Comment by zhouqunhuang** [comment]
Thank you very much! With your patient reply, I have now implemented the switch between MicrophoneSource and InternalAudioSource. But I can't have both MicrophoneSoure and InternalAudioSource on at the same time and I have to choose one or the other how do I get them both on?

**Comment by pedroSG94** [comment]
Hello,

Currently, only one video or audio source is supported.
You can try create a new custom AudioSource where you mix both but I'm not sure how to implement it.

**Comment by pedroSG94** [comment]
I will add this as a future feature but I can't give you a date for it

**Comment by zhouqunhuang** [comment]
Thank you very much! But I'm surprised that the microphone can't pick up the sound inside the speaker when I put it out there and it can't pick up the sound when it's pushed to the server, but it can pick up the human voice even if it's very low. I'm looking forward to your realization.

**Comment by zhouqunhuang** [comment]
Hello! I encountered an issue using your library in my project. I encountered an issue while starting the encoder:
![image](https://github.com/user-attachments/assets/df23cd79-5936-4c24-9538-66fe2916e999)
 Below is my error log. May I ask what caused this and how can I fix it. If you use the same device environment, your project will not fail to start.
===========================================================LOG======================
2024-10-10 15:53:22.173 13814-13814/cn.com.iqtouchlive E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cn.com.iqtouchlive, PID: 13814
    android.media.MediaCodec$CodecException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:2284)
        at com.pedro.encoder.BaseEncoder.initCodec(BaseEncoder.java:97)
        at com.pedro.encoder.BaseEncoder.start(BaseEncoder.java:83)
        at com.pedro.library.base.StreamBase.startSources(StreamBase.kt:379)
        at com.pedro.library.base.StreamBase.startStream(StreamBase.kt:152)
        at cn.com.iqtouchlive.service.IQLiveScreenService.startStream(IQLiveScreenService.java:513)
        at cn.com.iqtouchlive.service.IQLiveScreenService.showConnmect(IQLiveScreenService.java:493)
        at cn.com.iqtouchlive.service.IQLiveScreenService.changeButtonText(IQLiveScreenService.java:438)
        at cn.com.iqtouchlive.service.IQLiveScreenService.onClick(IQLiveScreenService.java:343)
        at android.view.View.performClick(View.java:7447)
        at android.view.View.performClickInternal(View.java:7424)
        at android.view.View.access$3700(View.java:841)
        at android.view.View$PerformClick.run(View.java:28728)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7869)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

**Comment by pedroSG94** [comment]
Do you have this error using the app example?
If not, I will need see your code implementation and the library version to know the error.

**Comment by zhouqunhuang** [comment]
Can you write a Java version of ScreenService? I feel like there might have been some issues when I switched from Kotlin to Java. I can implement streaming by copying your ScreenService into my project. So I can't understand Kotlin code. So I don't know where the problem lies?

**Comment by pedroSG94** [comment]
Hello,

I can write the Java version of that class in a branch but I can't reproduce the error like this because the code shared is uncompleted. 

Meanwhile, test in the app example using the kotlin example with your configuration to discard problem in the video/audio configuration used.

**Comment by zhouqunhuang** [comment]
thank you! I have already converted my Java to Kotlin and there is no longer this issue. But I still don't understand why I can't convert to Java. I can't find the reason either.

**Comment by pedroSG94** [comment]
Ok, I think that I detected the problem. Remember that in java this:
```java
genericStream.prepareVideo(width, height, vBitrate, rotation);
```
Is not equivalent to this:
```kotlin
genericStream.prepareVideo(width, height, vBitrate, rotation = rotation)
```

The reason is that prepareVideo is configured like this:
```kotlin
prepareVideo(width: Int, height: Int, bitrate: Int, fps: Int = 30, iFrameInterval: Int = 2,
    rotation: Int = 0, profile: Int = -1, level: Int = -1): Boolean
```

So that code in java is traduced to this in kotlin:
```kotlin
genericStream.prepareVideo(width, height, vBitrate, fps = rotation)
```

To fix it try this:
```java
genericStream.prepareVideo(width, height, vBitrate, 30, 2, rotation);
```

If it is not working I will continue with the code migration to Java. Also, I will add fews check in the code to avoid this problems in the future.

**Comment by zhouqunhuang** [comment]
Wow! So that's the reason. I tried using the code you provided and found that the code in Java can also run correctly! Thank you for your guidance.

**Comment by zhouqunhuang** [comment]
你好！我想请问下之前我录制屏幕并推流是可以听到麦克风的声音最近突然没有声音了。这种问题什么造成的

**Comment by zhouqunhuang** [comment]
Hello! I was wondering if you could help me with something. Previously, when I recorded the screen and streamed it, I could hear the microphone sound, but recently it suddenly stopped working. What could be causing this issue?

**Comment by pedroSG94** [comment]
Please, open other issue and explain it in detail. 
- Class used
- audio parameters
- audio type (internal, microphone, from file)
- Library versión
- Protocol
- logcat when the audio is not working
