### ISSUE TITLE
Video extract NullPointerException

### ISSUE THREAD

**Issue by noho501** [pedroSG94/RootEncoder#1595]
Hi @pedroSG94 ,

I am encountering many cases where the video does not include the formats retrieved from the link below, resulting in a NullPointerException error. I understand that a video needs to have all the specified formats to work properly, but I don’t understand why the same video works fine when transferred to another device.

In cases where the formats cannot be retrieved, could you set it to return `false` or another state to avoid the NullPointerException? From my experience, videos missing these fields can still stream normally. If you have a better solution, I would really appreciate your suggestion. 

Thank you very much!

You can found it here
https://github.com/pedroSG94/RootEncoder/blob/master/encoder/src/main/java/com/pedro/encoder/input/decoder/VideoDecoder.java#L57

```
if (mediaFormat != null) {
      width = mediaFormat.getInteger(MediaFormat.KEY_WIDTH);
      height = mediaFormat.getInteger(MediaFormat.KEY_HEIGHT);
      duration = mediaFormat.getLong(MediaFormat.KEY_DURATION);
      return true;
      //video decoder not supported
}
```

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at android.media.MediaFormat.getInteger(MediaFormat.java:1491)
	at com.pedro.encoder.input.decoder.VideoDecoder.extract(VideoDecoder.java:57)
	at com.pedro.encoder.input.decoder.BaseDecoder.initExtractor(BaseDecoder.java:67)
	at com.pedro.library.base.FromFileBase.prepareVideo(FromFileBase.java:152)
	at com.pedro.library.base.FromFileBase.prepareVideo(FromFileBase.java:187)
	at com.apptest.live.activity.LocalVideoActivity.prepare(LocalVideoActivity.kt:383)
	at com.apptest.live.activity.LocalVideoActivity.onLive(LocalVideoActivity.kt:475)
	at com.apptest.live.activity.LocalVideoActivity.initAction$lambda$14$lambda$13(LocalVideoActivity.kt:344)
	at com.apptest.live.activity.LocalVideoActivity.$r8$lambda$m-V5l8e-hJAEn_eugBnMpRbwmW8(Unknown Source:0)
	at com.apptest.live.activity.LocalVideoActivity$$ExternalSyntheticLambda8.onClick(D8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:7769)
	at android.view.View.performClickInternal(View.java:7742)
	at android.view.View.access$3700(View.java:856)
	at android.view.View$PerformClick.run(View.java:29326)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1074)
```

**Comment by pedroSG94** [comment]
Hello,

Thank you for the report. I will check it.

The reason about this crash is that each device have different decoders with different capabilities so maybe the video has an unsupported configuration for that device or the decoder selected is bugged.

**Comment by pedroSG94** [comment]
Can you share me a video file that crash to try reproduce the case or at least know the exact configuration of the video?

**Comment by noho501** [comment]
Yes, I will send you via email

**Comment by noho501** [comment]
Yes, I will upload it to Google Drive and send it to you via email. I'm not sure if it will work for you, because the same video works fine on another phone.

**Comment by noho501** [comment]
Hi @pedroSG94 ,

Could you please create a JitPack snapshot on the master branch, so I can check it again?

**Comment by pedroSG94** [comment]
Try with this gradle:
```gradle
implementation 'com.github.pedroSG94.RootEncoder:library:master-SNAPSHOT'
```
This should update automatically with the master changes

**Comment by pedroSG94** [comment]
This error should be solved now.

**Comment by noho501** [comment]
I confirm that it’s working now. Thanks for your help, @pedroSG94
