### ISSUE TITLE
ClosedWriteChannelException: The channel was closed

### ISSUE THREAD

**Issue by noho501** [pedroSG94/RootEncoder#1601]
Hi @pedroSG94 ,

We are encountering an issue during screen broadcasting on Facebook, where an error appears after about a minute. This problem only occurs on Facebook; streaming to YouTube works fine. This error didn’t appear before, but it has started showing up recently, possibly after a recent update.

Branch: Master
Screen broadcast settings: 720x1280, 30fps, bitrate: 500*1000
Platform: Facebook

I’ve attached the full log. Could you please provide any suggestions to help resolve this issue?
[OPPO-CPH2473-Android-14_2024-10-12_093032.txt.txt](https://github.com/user-attachments/files/17348581/OPPO-CPH2473-Android-14_2024-10-12_093032.txt.txt)

**Comment by pedroSG94** [comment]
Hello,

According with the logs, the videoinfo is setted multiple times doing that video packets is reset and maybe produce this error. To avoid it  I did a fix for it:
https://github.com/pedroSG94/RootEncoder/pull/1602

```gradle
  implementation 'com.github.pedroSG94.RootEncoder:library:c62693873d'
```

**Comment by pedroSG94** [comment]
I was able to reproduce the error. I'm working on it

**Comment by noho501** [comment]
Thank you so much. I am looking forward to your good news.

**Comment by pedroSG94** [comment]
For now, I detected that this is a bug in Ktor library because using java.io socket it is working fine.

**Comment by pedroSG94** [comment]
Fixed here:
https://github.com/pedroSG94/RootEncoder/commit/546ef083a9f704a563e9ec789a7176237db40c29

The problem was related with the soTimeout using a tls socket. I think it is a bug in the ktor library but I was able to solve it using withtimeout in read/write methods manually

**Comment by noho501** [comment]
Thank you so much, I will test it and let you know

**Comment by noho501** [comment]
Thank you for the fix. However, another issue still seems unresolved. I am trying to stream using the local file I attached, but after a second, it stops. Please check the log.

Log:
[OPPO-CPH2473-Android-14_2024-10-14_151002.txt](https://github.com/user-attachments/files/17360920/OPPO-CPH2473-Android-14_2024-10-14_151002.txt)

The video used for streaming:
https://drive.google.com/file/d/1ncjueHqJ8mIUdl7vSlsQ_7moYSP79mw8/view?usp=sharing

Thanks.

**Comment by pedroSG94** [comment]
Hello,

I don't understand that logs. It is a json
About the error, are you able to reproduce it using other device?

**Comment by noho501** [comment]
Hi,

Please see the new attached log. Yes, I can reproduce the issue on other devices (Android 12 & 14). It's the same error with this video (some videos still work): [Video link](https://drive.google.com/file/d/1ncjueHqJ8mIUdl7vSlsQ_7moYSP79mw8/view?usp=sharing).

[OPPO-CPH2473-Android-14_2024-10-14_1545.txt](https://github.com/user-attachments/files/17361385/OPPO-CPH2473-Android-14_2024-10-14_1545.txt)

**Comment by noho501** [comment]
Thank you for your confirmation. I am looking forward to your good news.

**Comment by pedroSG94** [comment]
After multiple tests I can confirm that it is not a bug in the library code, it is a bug in the MediaExtractor class. MediaExtractor is not able to extract frames from that video for some reason (audio is working). If you re encode the video using ffmpeg it is wofking fine so it is not a problem in the video config.

The only solution will be implement a new extractor without MediaExtractor class but the only viable alternative is use the extractor of ExoPlayer project. The problem is that ExoPlayer need min API version 19 but this project have min API version 16 so I have plan to do a full refactor to decoders that will allow change the extractor allowing set a extractor based on ExoPlayer and add that extractor to extra-sources module which use min API 21.

I will do this new feature for version 2.5.3 because this is a big change and I want avoid change more code in this version.

**Comment by pedroSG94** [comment]
Other alternative is use MediaPlayer class to get video frames and MediaExtractor for audio but I'm not sure if this solution is a good idea.

What do you think about it?. I tested this but it produce others limitations

**Comment by noho501** [comment]
Thank you for confirming. I also believe that using ExoPlayer is the best solution. I will wait for version 2.5.3 and test it once it's available.

**Comment by noho501** [comment]
Hi @pedroSG94 ,

After updating to version 2.5.4, the problem persists, and there are additional issues. The audio is distorted and plays slowly.

Here is the link to the video I streamed: [YouTube Live Video](https://www.youtube.com/live/F4HMzthUqdg).

Here is the original video: [Original Video](https://drive.google.com/file/d/1EEK4y1RPBGjCaEPhjGI9DI6toOR10dpu/view?usp=sharing).

Additionally, this video cannot be streamed; it says it is not supported: 
- [Video 1](https://drive.google.com/file/d/16_gTUaz8kgrwUfjZ7aPqPJSvIMy61R_t/view?usp=sharing)
- [Video 2](https://drive.google.com/file/d/1fSZiuM-z9A_Ez0vO_CVl5fcf_QNeEu2V/view?usp=sharing)

Best regards,

**Comment by pedroSG94** [comment]
Hello,

Thank you for the report. I will check it.

I'm developing an Extractor using Exoplayer extractor instead of MediaExtractor from Android but it is not ready yet so all should be working like in the version 2.5.2 (the video that freeze is not working yet video2)

I will check the new issues maybe related with the new decoder implementation and fix it.

**Comment by pedroSG94** [comment]
Hello,

I checked the first file but the error related with slowly audio is present in previous versions before the change so It is not a problem only in the last version but maybe it is fixeable (still checking it). 

About the not supported error, it is because I added an additional check in the decoder that force the video used to have duration that I think is the problem because the video is freeze. If the duration can't be extracted, the video extraction fail before start decoding to avoid reproduce video that will be invalid and freeze.

I will check the first video but the second and third video should be fixed using the new extractor instead the current extractor. I think that report a fail is better than let the user reproduce it and produce a freeze.

**Comment by pedroSG94** [comment]
I discovered the reason about the first video fail.

When you extract audio info from the first video using MediaExtractor or even with MediaMetadataRetriever the samplerate is 24000 but the real samplerate is 48000. This produce the slowly audio effect because the encoder is configured based on the decoder extracted value. If you hardcode the samplerate value all is working fine.

This seem that it is not a problem in the decoder code but more a problem in MediaExtractor class of Android. I'm looking if I can find a way to fix it

**Comment by pedroSG94** [comment]
I added a commit that implement a Media3Extractor using the exoplayer project dependency that improve a bit this problem but still produce problems:
https://github.com/pedroSG94/RootEncoder/commit/dcf669a9873651c3822caedf95dd685508be5171

**Comment by noho501** [comment]
Thank you! I’ll test it and report back to you.

**Comment by pedroSG94** [comment]
This new Extractor solve the problem with the first file but still have few problems using the second and third file (mostly with the second file).
Remember that you need change the extractor for video or audio using:
```kotlin
    genericFromFile.setAudioExtractor(Media3Extractor(this))
    genericFromFile.setVideoExtractor(Media3Extractor(this))
```

**Comment by noho501** [comment]
Hi @pedroSG94,

I am using the following dependencies:

```groovy
implementation 'com.github.pedroSG94.RootEncoder:library:2.5.4'
implementation ('com.github.pedroSG94.RootEncoder:extra-sources:2.5.4') {
    exclude module: 'UVCAndroid'
}
```

When I implement version 2.5.4 and try to import `import com.pedro.extrasources.extractor.Media3Extractor`, I receive the error: *Unresolved reference: extractor*. 

Do you know how to resolve this issue?

Thank you!

**Comment by pedroSG94** [comment]
Hello,

It isn't in the last release. Use this for now:
```gradle
  implementation 'com.github.pedroSG94.RootEncoder:library:73b7c9d43e'
```

**Comment by noho501** [comment]
Hi @pedroSG94 ,

I have tested new update. This version does not perform as well as version 2.5.2. While version 2.5.4 addresses some issues, it also introduces several new ones that were not present in version 2.5.2. 

1. **Video Auto-Stopping After Multiple Loops**  
   - Description: The video loops approximately 10 times and then stops automatically.  
   - Example: You can observe this behavior in the following live stream:  
     [[YouTube Link](https://youtube.com/live/5yHr4T_UTgQ)](https://youtube.com/live/5yHr4T_UTgQ)  
   - Test File: [[Google Drive File](https://drive.google.com/file/d/1xJJOGFvBIKdbSeJZNNB7VDlUhxv8kuIi/view?usp=sharing)](https://drive.google.com/file/d/1xJJOGFvBIKdbSeJZNNB7VDlUhxv8kuIi/view?usp=sharing)

2. **Sound Issues in Video Playback**  
   - Description: The audio quality has changed compared to previous versions. This issue appears in the following example:  
     [[YouTube Link](https://www.youtube.com/live/uQHaF8Qslzg)](https://www.youtube.com/live/uQHaF8Qslzg)  
   - Test File: [[Google Drive File](https://drive.google.com/file/d/1EEK4y1RPBGjCaEPhjGI9DI6toOR10dpu/view?usp=sharing)](https://drive.google.com/file/d/1EEK4y1RPBGjCaEPhjGI9DI6toOR10dpu/view?usp=sharing)

This log might help:
[log_loop_stream_video_failed.txt](https://github.com/user-attachments/files/17879028/log_loop_stream_video_failed.txt)

Best regards,

**Comment by pedroSG94** [comment]
Hello,

In the case 1 the problem seem that the loop failed but only with the audio because the video continue until the end but no the audio. I think that YouTube closed the stream because the audio stopped to work. YouTube need audio and video to work so after fail in the audio loop the stream stopped.

In the case 2, this is already fixed. Since it is a bug in MediaExtractor android class I did an implementation using Media3 library of androidx that fix the problem. You can test it using this method:
```kotlin
genericFromFile.setVideoExtractor(Media3Extractor(context))
genericFromFile.setAudioExtractor(Media3Extractor(context))
```

This allow you change the video or audio extractor. This could help you to fix both cases but I'm sure that if you change the audio extractor the second case will be fixed.
I will investigate the first case using the android MediaExtractor class.

**Comment by noho501** [comment]
Hi,

Have you found any solution to resolve the first case?

**Comment by pedroSG94** [comment]
Hello,

I did a fix for it. Try this gradle:
```gradle
  implementation 'com.github.pedroSG94.RootEncoder:library:2707c46770'
```

**Comment by noho501** [comment]
Hi,

It cannot loop; it crashes instead. Below is the crash log for your reference.

```
Fatal Exception: java.lang.NoSuchMethodError: No virtual method reset(Landroid/view/Surface;)V in class Lcom/pedro/encoder/input/decoder/VideoDecoder; or its super classes (declaration of 'com.pedro.encoder.input.decoder.VideoDecoder' appears in base.apk!classes4.dex)
       at com.pedro.library.base.FromFileBase$3.onLoop(FromFileBase.java:772)
       at com.pedro.encoder.input.decoder.BaseDecoder.decode(BaseDecoder.java:193)
       at com.pedro.encoder.input.decoder.BaseDecoder.lambda$start$0(BaseDecoder.java:78)
       at com.pedro.encoder.input.decoder.BaseDecoder.$r8$lambda$qOySR8SziHjvM-o-o93p4pBV9MY()
       at com.pedro.encoder.input.decoder.BaseDecoder$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)
        
```

**Comment by pedroSG94** [comment]
I don't understand that error. I'm not able to reproduce it, it seems a compilation error.
Are you using that commit version for all dependencies related to my project? If the problem persist you can test with my project in the last commit of master branch

**Comment by bententuan** [comment]
> Hello,
> 
> I did a fix for it. Try this gradle:
> 
>   implementation 'com.github.pedroSG94.RootEncoder:library:2707c46770'

Hi @pedroSG94 , sorry but how can i properly implement this version? It can't download as you can see in this pic:

![Image](https://github.com/user-attachments/assets/7726e43a-1a77-4e00-acc2-3b7a657ec668)

**Comment by pedroSG94** [comment]
Hello,

I just released a new version that include this fix. Please use version 2.5.7
I will close the issue after your confirmation

**Comment by datdo7549** [comment]
Hi @pedroSG94 , I just checked your source code. I cloned your project and ran it, and I noticed something unusual. I am using the version 2.5.7

First, i've set the Media3Extractor for AudioExtractor (you can see in attached image)

<img width="1034" alt="Image" src="https://github.com/user-attachments/assets/b86d74d6-fb76-4f22-ae56-d485a7416a7b" />

Then, i put the log like this in the onLoop function of FromFileBase class:

<img width="1034" alt="Image" src="https://github.com/user-attachments/assets/435f477e-4ea5-4e5d-ac36-a54dac95234d" />

And the result is, the video can only be played once, and right at the end of the video, I checked the Logcat and saw that this onLoop function was run twice in a very short period of time (this is not normal at all)

<img width="1043" alt="Image" src="https://github.com/user-attachments/assets/e8dcad00-daf4-4b6d-b74a-d08df971e0f7" />

Here are the link of the video for testing and the result video:
https://drive.google.com/file/d/12XxeVylTBo1Ur8XIXlazrFCstYbV0qNU/view?usp=sharing

**Comment by pedroSG94** [comment]
Hello,

That callback is called one time for each track (audio and video). Maybe the error is related with that. I will check it

**Comment by datdo-atg** [comment]
> Hello,
> 
> That callback is called one time for each track (audio and video). Maybe the error is related with that. I will check it

Well thank you, and I think you should focus on this: https://github.com/pedroSG94/RootEncoder/blob/588f1e1c559f8c2269f6a9631633f33319125b85/encoder/src/main/java/com/pedro/encoder/input/decoder/BaseDecoder.java#L216 
Because there will be another error that sometimes the **finished** condition will be true because extractor.advance() returns False, even though the video is not completely finished.

**Comment by datdo7549** [comment]
> Hello,
> 
> That callback is called one time for each track (audio and video). Maybe the error is related with that. I will check it

Well thank you, and I think you should focus on this: https://github.com/pedroSG94/RootEncoder/blob/588f1e1c559f8c2269f6a9631633f33319125b85/encoder/src/main/java/com/pedro/encoder/input/decoder/BaseDecoder.java#L216 
Because there will be another error that sometimes the **finished** condition will be true because extractor.advance() returns False, even though the video is not completely finished.

**Comment by pedroSG94** [comment]
> > Hello,
> > That callback is called one time for each track (audio and video). Maybe the error is related with that. I will check it
> 
> Well thank you, and I think you should focus on this:
> 
> [RootEncoder/encoder/src/main/java/com/pedro/encoder/input/decoder/BaseDecoder.java](https://github.com/pedroSG94/RootEncoder/blob/588f1e1c559f8c2269f6a9631633f33319125b85/encoder/src/main/java/com/pedro/encoder/input/decoder/BaseDecoder.java#L216)
> 
> Line 216 in [588f1e1](/pedroSG94/RootEncoder/commit/588f1e1c559f8c2269f6a9631633f33319125b85)
> 
>  finished = !extractor.advance(); 
> 
> Because there will be another error that sometimes the **finished** condition will be true because extractor.advance() returns False, even though the video is not completely finished.

Ok, can you share me the video used to reproduce this error?

**Comment by datdo7549** [comment]
> > > Hello,
> > > That callback is called one time for each track (audio and video). Maybe the error is related with that. I will check it
> > 
> > 
> > Well thank you, and I think you should focus on this:
> > [RootEncoder/encoder/src/main/java/com/pedro/encoder/input/decoder/BaseDecoder.java](https://github.com/pedroSG94/RootEncoder/blob/588f1e1c559f8c2269f6a9631633f33319125b85/encoder/src/main/java/com/pedro/encoder/input/decoder/BaseDecoder.java#L216)
> > Line 216 in [588f1e1](/pedroSG94/RootEncoder/commit/588f1e1c559f8c2269f6a9631633f33319125b85)
> > finished = !extractor.advance();
> > Because there will be another error that sometimes the **finished** condition will be true because extractor.advance() returns False, even though the video is not completely finished.
> 
> Ok, can you share me the video used to reproduce this error?

Here you are:

**Comment by pedroSG94** [comment]
Hello,

This commit avoid call onLoop method 2 times for each decoder:
https://github.com/pedroSG94/RootEncoder/commit/6cf5094183c18ff366745d668952152f1bd5ce5e

Test with the last commit of master:
```gradle
  implementation 'com.github.pedroSG94.RootEncoder:library:dd19d939c1'
```

**Comment by datdo-atg** [comment]
> Hello,
> 
> This commit avoid call onLoop method 2 times for each decoder: [6cf5094](https://github.com/pedroSG94/RootEncoder/commit/6cf5094183c18ff366745d668952152f1bd5ce5e)
> 
> Test with the last commit of master:
> 
>   implementation 'com.github.pedroSG94.RootEncoder:library:dd19d939c1'

Hello,

I will test it and give you the result asap.

Thank you

**Comment by datdo7549** [comment]
> Hello,
> 
> This commit avoid call onLoop method 2 times for each decoder: [6cf5094](https://github.com/pedroSG94/RootEncoder/commit/6cf5094183c18ff366745d668952152f1bd5ce5e)
> 
> Test with the last commit of master:
> 
>   implementation 'com.github.pedroSG94.RootEncoder:library:dd19d939c1'

Hello,
I will test it and give you the result asap.

Thank you

**Comment by datdo7549** [comment]
> Hello,
> 
> This commit avoid call onLoop method 2 times for each decoder: [6cf5094](https://github.com/pedroSG94/RootEncoder/commit/6cf5094183c18ff366745d668952152f1bd5ce5e)
> 
> Test with the last commit of master:
> 
>   implementation 'com.github.pedroSG94.RootEncoder:library:dd19d939c1'

Hello, 
It seems that the issue with automatically stopping the loop has been fixed. However, there is still one issue I mentioned: Occasionally, the video automatically restarts from the beginning even though it hasn’t finished playing.

Here is the issue video: https://drive.google.com/file/d/1CMJwApYTWGK5bqIwyD49bu5Ikcx3v5Dg/view?usp=sharing
The testing video: https://drive.google.com/file/d/12XxeVylTBo1Ur8XIXlazrFCstYbV0qNU/view?usp=sharing

Thanks,

**Comment by datdo-atg** [comment]
Hello @pedroSG94 , can you reproduce the issue? Until now, the problem still occurs on the latest version.

**Comment by datdo7549** [comment]
Hello @pedroSG94 , can you reproduce the issue? Until now, the problem still occurs on the latest version.

**Comment by pedroSG94** [comment]
Hello,

No, I'm not able to reproduce it.

**Comment by noho501** [comment]
Hi @pedroSG94 ,

After updating to **version 2.5.8**, the issue has reappeared. I am able to stream to **YouTube** normally, but **Facebook** streaming fails.

Here is part of the log showing the error:

```
22:44:46.962  I  send Command(name='publish', transactionId=5, timeStamp=1, streamId=1, data=[AmfString value: publish, AmfNumber value: 5.0, AmfNull, AmfString value: , AmfString value: live], bodySize=30)
22:44:46.962  I  success response received from createStream
22:44:47.055  E  connection error (Ask Gemini)
                 java.io.EOFException: Channel is already closed
...
22:44:47.089  E  GL already released
```

I’ve attached the full log file for your reference.  
Could you please help me check what might be causing the problem?

Thank you so much for your support! Looking forward to your response.

[Log_Error.txt](https://github.com/user-attachments/files/19376836/Log_Error.txt)

**Comment by pedroSG94** [comment]
Hello,

I did a commit to solve it:
https://github.com/pedroSG94/RootEncoder/commit/c3087bd58bb570d0fa299235675854cda60e6dcc
This seem a bug in the ktor library with tls timeout
Test master branch and let me know if the problem is solved. I will update a release in that case

**Comment by noho501** [comment]
Thanks, I will check and let you know

**Comment by noho501** [comment]
Hi @pedroSG94 ,

I’m unable to fetch the dependencies from the `master` branch. Could you please take a look?

Here’s my current setup:

```gradle
implementation 'com.github.pedroSG94.RootEncoder:library:master-SNAPSHOT'
implementation ('com.github.pedroSG94.RootEncoder:extra-sources:master-SNAPSHOT') {
    exclude module: 'UVCAndroid'
}
```

However, I’m receiving the following error:

```
Could not resolve com.github.pedroSG94.RootEncoder:library:master-SNAPSHOT.
```

Could you please check if there’s any issue with the `master-SNAPSHOT` deployment?

Thank you in advance! 🙏

**Comment by pedroSG94** [comment]
Hello,

Seems that the last commit is not deployed yet. I'm not sure the reason maybe a problem with github servers. 
I will notify you here when all is ready

**Comment by pedroSG94** [comment]
Try this:
```gradle
implementation 'com.github.pedroSG94.RootEncoder:library:c3087bd58b'
implementation ('com.github.pedroSG94.RootEncoder:extra-sources:c3087bd58b') {
    exclude module: 'UVCAndroid'
}
```

**Comment by noho501** [comment]
Thank you! It’s working perfectly now, and the issue has been resolved.

Really appreciate your support! 🙏

**Comment by pedroSG94** [comment]
version 2.5.9 is available with the fix
