### ISSUE TITLE
2.5.4 connection error

### ISSUE THREAD

**Issue by alexsafe** [pedroSG94/RootEncoder#1654]
Hi, 

This is a follow-up to #1652 
So my connection string that works with 2.5.0 is rtmp://rtmp-auto.millicast.com:[port]/v2/pub/$streamName?token=$streamToken. I'm using dolby and they have a $streamName?token=$streamToken  for the Rtmp publish stream name. 

The string that passes for 2.5.4 is rtmp://rtmp-auto.millicast.com:[port]/v2/pub/$streamName?$streamToken but that's missing the `?token =` part which leads to 

`RtmpClient               I  success response received from createStream

RtmpClient               E  connection error (Ask Gemini)
                                         java.io.EOFException: Not enough data available
                                         	at io.ktor.utils.io.ByteReadChannelOperationsKt.readByte(ByteReadChannelOperations.kt:48)
                                         	at io.ktor.utils.io.ByteReadChannelOperationsKt$readByte$1.invokeSuspend(Unknown Source:13)
                                         	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                         	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
                                         	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
                                         	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
                                         	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
                                         	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
                                         	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
                                         	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)

RtmpSurfaceStream        E  Connection failed: Error configure stream, Not enough data available `

Any idea on how to make these work together?

**Comment by pedroSG94** [comment]
Hello,

Fixed here:
https://github.com/pedroSG94/RootEncoder/commit/dbd7a9ed1e636b3d15f47034ef48a8a130141a2d

This will be available in the next version. You can use this gradle meanwhile:
```gradle
  implementation 'com.github.pedroSG94.RootEncoder:library:dbd7a9ed1e'
```

**Comment by alexsafe** [comment]
Awesome thanks
