### ISSUE TITLE
Crash at ManagerRender.drawScreen

### ISSUE THREAD

**Issue by insidefun** [pedroSG94/RootEncoder#744]
RTMP, OpenGlView, No filters, Front camera

```
Fatal Exception: java.lang.RuntimeException: drawScreen end. GL error: 1285
       at com.pedro.encoder.utils.gl.GlUtil.checkGlError(GlUtil.java:126)
       at com.pedro.encoder.input.gl.render.ScreenRender.draw(ScreenRender.java:115)
       at com.pedro.encoder.input.gl.render.ManagerRender.drawScreen(ManagerRender.java:66)
       at com.pedro.rtplibrary.view.OpenGlView.run(OpenGlView.java:144)
       at java.lang.Thread.run(Thread.java:929)
```

**Comment by pedroSG94** [comment]
That error means OutOfMemory. 
Do you have any way to reproduce it?
Do you have this error with all devices?

**Comment by insidefun** [comment]
![image](https://user-images.githubusercontent.com/9580252/102089031-bfa9ee00-3e2c-11eb-990c-37b3db12d7a5.png)

Based on firebase info, devices had enought memory

**Comment by pedroSG94** [comment]
Acording with android documentation 1285 is out of memory:
https://developer.android.com/reference/android/opengl/GLES20#GL_OUT_OF_MEMORY

The question is, why only in certains devices?
Do you have any way to know if your user is streaming long time before get this crash? Maybe I'm not releasing something properly

**Comment by linean** [comment]
I'm facing a similar issue mostly on Samsung devices
<img width="485" alt="image" src="https://user-images.githubusercontent.com/17886739/166695206-fa2ebe09-cbb1-4d8c-b565-fb26bb312893.png">

```
Fatal Exception: java.lang.RuntimeException: drawScreen end. GL error: 1285
       at com.pedro.encoder.utils.gl.GlUtil.checkGlError(GlUtil.java:142)
       at com.pedro.encoder.input.gl.render.ScreenRender.draw(ScreenRender.java:131)
       at com.pedro.encoder.input.gl.render.ManagerRender.drawScreen(ManagerRender.java:76)
       at com.pedro.rtplibrary.view.OpenGlView.run(OpenGlView.java:189)
       at java.lang.Thread.run(Thread.java:764)
```

After debugging with the Android Studio profiler I didn't find any leaks 😞

**Comment by pedroSG94** [comment]
Hello,

If possible, let me know if you are using any filter and which one.
Also, if you can get time streaming until you get that crash, device model and android api.

This crash seems really difficult to reproduce and I'm not sure about the reason so it is hard to fix.

**Comment by linean** [comment]
I'm using `BlurFilterRender`. These crashes are not super frequent so from my perspective it's a low prio thing.

Based on the logs, crashes are pretty random. Sometimes they occur after a few seconds of streaming and somethimes after user leaves the screen. It's also possible that these are caused by other leakage elsewhere in the application 🤷 

If I manage to find some pattern or more details I'll post them here 🤞

**Comment by linean** [comment]
Unfortunately no, crashes seems pretty random. Luckily they doesn't affect a significant number of users 🤷

**Comment by pedroSG94** [comment]
If anyone could find a way to reproduce the error report it here.
Since in OpenGL documentation the error code is an out of memory I only can assume a GPU memory overflow.
If you have any way to report GPU memory state when you receive that error, this could be helpful

**Comment by minonger** [comment]
I have the same error on Samsung Galaxy S21.
It's happen all the time. Without any filter.
![openGL_crash-01](https://user-images.githubusercontent.com/8503429/198411619-4821edcf-ffc7-49a1-aa84-e2787910a990.jpg)

**Comment by mkrn** [comment]
@minonger were you able to fix it? Are there any special conditions to it happening? Like using WiFi/5G / reconnecting / going to background and back?

**Comment by altunbayrakergun** [comment]
Have you solved it? I'm facing this problem now. I'm using both ImageFilter and TextFilter together. I'm still in development. There were no problems in short-term tests. I suddenly encountered this error while broadcasting for more than 20 minutes. Test device is Redmi Note 11 pro. 3.5gb free memory and 35gb available disk. I'm using mobile internet.

**Comment by pedroSG94** [comment]
Hello,

This error is really random and I'm not able to reproduce it consistently to solve.

If you can reproduce it, test this and tell me the result:
- Try to stream without filters to discard problems with filters. If you can't reproduce the error without filters, then test with only one filter to try find the filter that produce problems.
- If you are streaming in background or you have rotation support. Try to stream in foreground all time and block screen orientation. This is to discard a problem related with the preview lifecycle.

Remember that this is an out of memory. Can you check the GPU memory usage? Maybe you can find a pattern

**Comment by altunbayrakergun** [comment]
Thank you for quick reply @pedroSG94 . 
Tests still continue. So propably I'll reproduce it. App currently doesn't support rotation. It only supports landscape and only streams foreground. I thought maybe the behavior was being disrupted for a reason like "preventing accidental screen touching".
I'll let you know immediately when reproduce it again.

**Comment by pedroSG94** [comment]
Hello,

I did a refactor to GlInterface (OpenGlView and GlStreamInterface) that maybe solved this error.
If possible try update the libary to version 2.3.7 and let me know if the problem is solved or reduced.

**Comment by altunbayrakergun** [comment]
I followed the user experience for a while and found the error. The activity was set to sensorlandscape. This error occurred when the user made a movement that caused a 180-degree rotation while holding the device. After changing the sensorlandscape setting to landscape, the problem disappeared. Also thank you for your revision. I will include it in the next refactoring process.

**Comment by altunbayrakergun** [comment]
It is worth adding that the problem only occurred if the screen was rotated while using filters. There is no problem with rotation when there is no filter.

**Comment by Feureth** [comment]
Hi @pedroSG94,
Today I have found that this issue occurs for `AndroidViewFilterRender`, if it has `isHardwareMode` forced to be `false`. I've not checked any other filter, my orientation is always horizontal.
I hope, it will help you with finding solution.

**Comment by pedroSG94** [comment]
Hello,

@Feureth are you using library version 2.4.0?

**Comment by Feureth** [comment]
Yes

**Comment by pedroSG94** [comment]
Hello,

That error is GL_INVALID_VALUE.
Normally produced because a parameter is invalid.
Do you have more info about the error? can you reproduce it?




> Fatal Exception: java.lang.RuntimeException: initGl end. GL error: 1281
>       at com.pedro.encoder.utils.gl.GlUtil.checkGlError(GlUtil.java:144)
>       at com.pedro.encoder.input.gl.render.filters.BaseFilterRender.initGl(BaseFilterRender.java:51)
>       at com.pedro.encoder.input.gl.render.MainRender.addFilter(MainRender.kt:99)
>       at com.pedro.encoder.input.gl.render.MainRender.setFilterAction(MainRender.kt:148)
>       at com.pedro.library.view.OpenGlView.draw(OpenGlView.java:251)
>       at com.pedro.library.view.OpenGlView.lambda$onFrameAvailable$6(OpenGlView.java:347)
>       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>       at java.lang.Thread.run(Thread.java:923)
>       ```

In this case the error is produced adding a filter. Do you know the filter used in this case and possible values?

**Comment by linean** [comment]
Unfortunately I'm not able to reproduce it. It happens to less than 0,1% of all users so it's not that bad. I'm using `BlurFilterRender`.

It seems to happen more on older devices.
<img width="568" alt="image" src="https://github.com/user-attachments/assets/f8e0d915-798b-4238-bf01-f5d7bd875bff">

**Comment by pedroSG94** [comment]
Seems that the error is usually in Samsung devices. Can you show me device models?

**Comment by linean** [comment]
Sure

<img width="566" alt="image" src="https://github.com/user-attachments/assets/3df36521-cbd3-4e1a-a88d-acea7a6ea0d3">

<img width="570" alt="image" src="https://github.com/user-attachments/assets/0d88fde5-e906-4d24-9917-371d4434746b">

<img width="569" alt="image" src="https://github.com/user-attachments/assets/72630790-d205-499d-8045-fad447a49a66">

**Comment by pedroSG94** [comment]
Ok, I will try investigate it. 
According with internet, this maybe is an error compiling the shader but it has no sense for me (in that case this should crash always in that model. Maybe an error reading the shader from disk?

**Comment by linean** [comment]
I didn't dive deep into the implementation details, so I'm not able to tell. I'm not really bothered by this crash, but I thought I'd share that 1285 turned into 1281 😇

**Comment by pedroSG94** [comment]
Any crash report is really welcome and know that the error 1285 is gone are good news.
I hope that, this error (1281) is less frequent than the other (1285). In this case, at least, it is a step in the good direction. :)

**Comment by pedroSG94** [comment]
I updated the library with a fix that could help for this case. instead of let opengl fail after create shaders and programs, now the library will throw an error depend of the moment that opengl fail, this way we can get more info about the error 1281 and fix it in nexts commits.
Try to update the library to version 2.4.7

**Comment by danielhergil** [comment]
Hello everyone, I do not know if this thread is still alive, but I was fighting with a very similar error and I could fix it. In my case, it was an error of this type:

`Fatal Exception: java.lang.RuntimeException: drawCamera start. GL error: 1281
       at com.pedro.encoder.utils.gl.GlUtil.checkGlError(GlUtil.java:132)
       at com.pedro.encoder.input.gl.render.CameraRender.draw(CameraRender.java:95)
       at com.pedro.encoder.input.gl.render.MainRender.drawOffScreen(MainRender.kt:60)
       at com.pedro.library.view.GlStreamInterface.draw(GlStreamInterface.kt:209)
       at com.pedro.library.view.GlStreamInterface.onFrameAvailable$lambda$9(GlStreamInterface.kt:268)
       at com.pedro.library.view.GlStreamInterface.$r8$lambda$BAtYl6ZVCZbXX960JSr5g3IQUyw()
       at com.pedro.library.view.GlStreamInterface$$ExternalSyntheticLambda2.run(D8$$SyntheticClass)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)`

It was happening when the user apply the changes in the app to use different video/audio encoder, fps, resolution and some other streaming parameters. So in my code, after apply the changes, I stopPreview and prepareVideo/Audio with the new parameters. 

After this, the crash happened in some devices. What I did is create a coroutine where I first clearFilters, then I stopPreview, and then I delay(500), then everything else (prepareVideo/Audio, etc). With the delay I give time for passing the new parameters to the camera when it is created.

I don't know if this could help to anyone but this worked for me.

**Comment by danielhergil** [comment]
Sure! The library version I am using is "2.5.5" currently. This is the portion of code where I have applied the changes that solved the issue in my case.

```
SettingsMenu(
                    visible = isSettingsMenuVisible,
                    screenWidth = screenWidth,
                    screenHeight = screenHeight,
                    isStreaming = isStreaming,
                    selectedCameraSource = selectedCameraSource,
                    onCameraSourceChange = { selectedCameraSource = it },
                    selectedAudioSource = selectedAudioSource,
                    onAudioSourceChange = { selectedAudioSource = it },
                    selectedVideoEncoder = selectedVideoEncoder,
                    onVideoEncoderChange = { selectedVideoEncoder = it },
                    selectedAudioEncoder = selectedAudioEncoder,
                    onAudioEncoderChange = { selectedAudioEncoder = it },
                    selectedBitrate = selectedBitrate,
                    onBitrateChange = { selectedBitrate = it },
                    selectedFPS = selectedFPS,
                    onFPSChange = { selectedFPS = it },
                    selectedResolution = selectedResolution,
                    onResolutionChange = { selectedResolution = it },
                    streamUrl = streamUrl,
                    onStreamUrlChange = { streamUrl = it },
                    availableVideoCodecs = getAvailableVideoCodecs(),
                    availableAudioCodecs = getAvailableAudioCodecs(),
                    onApply = {

                        coroutineScope.launch {
                            if (!isStreaming) {

                                genericStream.getGlInterface().clearFilters()

                                genericStream.stopPreview()

                                delay(500)

                                // Apply new resolution settings.
                                when (selectedResolution) {
                                    "1080p" -> {
                                        videoWidth = 1920
                                        videoHeight = 1080
                                    }
                                    "720p" -> {
                                        videoWidth = 1280
                                        videoHeight = 720
                                    }
                                }
                                videoBitrate = selectedBitrate

                                // Save settings.
                                sharedPreferences.edit().apply {
                                    putInt("videoWidth", videoWidth)
                                    putInt("videoHeight", videoHeight)
                                    putInt("videoBitrate", videoBitrate)
                                    putString("streamUrl", streamUrl)
                                    apply()
                                }

                                // Update codecs.
                                enumAudioMapping[selectedAudioEncoder]?.let { audioCodec ->
                                    genericStream.setAudioCodec(audioCodec)
                                    Log.d("CodecCheck", "Set audio codec to: $audioCodec")
                                }
                                enumVideoMapping[selectedVideoEncoder]?.let { videoCodec ->
                                    genericStream.setVideoCodec(videoCodec)
                                    Log.d("CodecCheck", "Set video codec to: $videoCodec")
                                }

                                // Prepare video and audio with new settings.
                                genericStream.prepareVideo(videoWidth, videoHeight, videoBitrate, selectedFPS.toInt())
                                genericStream.prepareAudio(audioSampleRate, audioIsStereo, audioBitrate)

                                // Restart preview using the stored SurfaceView.
                                surfaceViewRef.value?.let { surfaceView ->
                                    genericStream.startPreview(surfaceView)
                                } ?: run {
                                    showToast("Error: SurfaceView not available")
                                }

                                // Update video source based on camera source setting.
                                if (selectedCameraSource == "USB Camera") {
                                    genericStream.changeVideoSource(CameraUvcSource())
                                } else {
                                    val newCameraSource = Camera2Source(context)
                                    genericStream.changeVideoSource(newCameraSource)
                                    activeCameraSource = newCameraSource
                                }
                                // Update audio source.
                                if (selectedAudioSource == "USB Mic") {
                                    genericStream.changeAudioSource(MicrophoneSource(MediaRecorder.AudioSource.MIC))
                                } else {
                                    genericStream.changeAudioSource(audio)
                                }
                            } else {
                                videoBitrate = selectedBitrate
                                genericStream.setVideoBitrateOnFly(videoBitrate)
                            }
                            isSettingsMenuVisible = false
                        }
                    },
                    onClose = { isSettingsMenuVisible = false }
                )
```

The devices that I tested failed were Pixel 7 Pro and Samsung Galaxy S20 FE. Before applying those changes I didnt have the coroutine with the delay and it was working in Samsung Galaxy Note 10+ and Samsung Galaxy S22 Ultra.

If more info is needed, I am happy to help!

**Comment by pedroSG94** [comment]
> Sure! The library version I am using is "2.5.5" currently. This is the portion of code where I have applied the changes that solved the issue in my case.
> 
> ```
> SettingsMenu(
>                     visible = isSettingsMenuVisible,
>                     screenWidth = screenWidth,
>                     screenHeight = screenHeight,
>                     isStreaming = isStreaming,
>                     selectedCameraSource = selectedCameraSource,
>                     onCameraSourceChange = { selectedCameraSource = it },
>                     selectedAudioSource = selectedAudioSource,
>                     onAudioSourceChange = { selectedAudioSource = it },
>                     selectedVideoEncoder = selectedVideoEncoder,
>                     onVideoEncoderChange = { selectedVideoEncoder = it },
>                     selectedAudioEncoder = selectedAudioEncoder,
>                     onAudioEncoderChange = { selectedAudioEncoder = it },
>                     selectedBitrate = selectedBitrate,
>                     onBitrateChange = { selectedBitrate = it },
>                     selectedFPS = selectedFPS,
>                     onFPSChange = { selectedFPS = it },
>                     selectedResolution = selectedResolution,
>                     onResolutionChange = { selectedResolution = it },
>                     streamUrl = streamUrl,
>                     onStreamUrlChange = { streamUrl = it },
>                     availableVideoCodecs = getAvailableVideoCodecs(),
>                     availableAudioCodecs = getAvailableAudioCodecs(),
>                     onApply = {
> 
>                         coroutineScope.launch {
>                             if (!isStreaming) {
> 
>                                 genericStream.getGlInterface().clearFilters()
> 
>                                 genericStream.stopPreview()
> 
>                                 delay(500)
> 
>                                 // Apply new resolution settings.
>                                 when (selectedResolution) {
>                                     "1080p" -> {
>                                         videoWidth = 1920
>                                         videoHeight = 1080
>                                     }
>                                     "720p" -> {
>                                         videoWidth = 1280
>                                         videoHeight = 720
>                                     }
>                                 }
>                                 videoBitrate = selectedBitrate
> 
>                                 // Save settings.
>                                 sharedPreferences.edit().apply {
>                                     putInt("videoWidth", videoWidth)
>                                     putInt("videoHeight", videoHeight)
>                                     putInt("videoBitrate", videoBitrate)
>                                     putString("streamUrl", streamUrl)
>                                     apply()
>                                 }
> 
>                                 // Update codecs.
>                                 enumAudioMapping[selectedAudioEncoder]?.let { audioCodec ->
>                                     genericStream.setAudioCodec(audioCodec)
>                                     Log.d("CodecCheck", "Set audio codec to: $audioCodec")
>                                 }
>                                 enumVideoMapping[selectedVideoEncoder]?.let { videoCodec ->
>                                     genericStream.setVideoCodec(videoCodec)
>                                     Log.d("CodecCheck", "Set video codec to: $videoCodec")
>                                 }
> 
>                                 // Prepare video and audio with new settings.
>                                 genericStream.prepareVideo(videoWidth, videoHeight, videoBitrate, selectedFPS.toInt())
>                                 genericStream.prepareAudio(audioSampleRate, audioIsStereo, audioBitrate)
> 
>                                 // Restart preview using the stored SurfaceView.
>                                 surfaceViewRef.value?.let { surfaceView ->
>                                     genericStream.startPreview(surfaceView)
>                                 } ?: run {
>                                     showToast("Error: SurfaceView not available")
>                                 }
> 
>                                 // Update video source based on camera source setting.
>                                 if (selectedCameraSource == "USB Camera") {
>                                     genericStream.changeVideoSource(CameraUvcSource())
>                                 } else {
>                                     val newCameraSource = Camera2Source(context)
>                                     genericStream.changeVideoSource(newCameraSource)
>                                     activeCameraSource = newCameraSource
>                                 }
>                                 // Update audio source.
>                                 if (selectedAudioSource == "USB Mic") {
>                                     genericStream.changeAudioSource(MicrophoneSource(MediaRecorder.AudioSource.MIC))
>                                 } else {
>                                     genericStream.changeAudioSource(audio)
>                                 }
>                             } else {
>                                 videoBitrate = selectedBitrate
>                                 genericStream.setVideoBitrateOnFly(videoBitrate)
>                             }
>                             isSettingsMenuVisible = false
>                         }
>                     },
>                     onClose = { isSettingsMenuVisible = false }
>                 )
> ```
> 
> The devices that I tested failed were Pixel 7 Pro and Samsung Galaxy S20 FE. Before applying those changes I didnt have the coroutine with the delay and it was working in Samsung Galaxy Note 10+ and Samsung Galaxy S22 Ultra.
> 
> If more info is needed, I am happy to help!

I assume that remove that delay(500) is enough to reproduce the error. Can you tell me if the error is 100% reproducible or this happens only sometimes?

**Comment by danielhergil** [comment]
I have already tested. In Samsung Galaxy 20 FE (the one that had the error) if I remove the delay(500) it crashes with the `drawCamera start. GL error: 1281`. I have also removed the comment in delay(500) to test it again, and it worked in the same device. 

What I assume from this, is that in some devices, it needs some time to process the data that is passes to the camera instance because otherwise, it can pass invalid values to the camera not being able to render. But I may be wrong, I am not very familiar with Android dev, but it what logic says to me.

I hope it can be helpful.

**Comment by pedroSG94** [comment]
Hello,

I did changes for this but I'm not able to reproduce it. To reproduce the case I tried this without luck:
```kotlin
    bSwitchCamera.setOnClickListener {
      CoroutineScope(Dispatchers.IO).launch {
        genericStream.getGlInterface().clearFilters()
        genericStream.stopPreview()
        // Prepare video and audio with new settings.
        genericStream.prepareVideo(1920, 1080, 5000 * 1000, 30)
        genericStream.prepareAudio(32000, true, 128 * 1000)
        genericStream.startPreview(surfaceView)
      }
    }
```
Here:
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/rotation/CameraFragment.kt#L158


Can you test with this compilation and let me know if the error is still present?
```gradle
implementation 'com.github.pedroSG94.RootEncoder:library:8fdb2831d1'
```

**Comment by danielhergil** [comment]
Hello Pedro, I can confirm that the commit `8fdb2831d1 ` it is working in Samsung Galaxy 20 FE when I remove the delay in my code. In my case, i have just tested the clearFilters and stopPreview, and when the new camera parameters apply, it does not crash anymore in that device.

What you have changed seems to be working, at least in the devices I had where it crashed before.

I have also tested the changes in the device it never crashed (Samsung Galaxy Note 10+) and it keep without crashing as well.

**Comment by pedroSG94** [comment]
Hello,

Thank you for the tests. I will marge that branch and mark this as solved.
