### ISSUE TITLE
RTMPHeader Error: "Unknown message type byte: 79"

### ISSUE THREAD

**Issue by CubitSpeed** [pedroSG94/RootEncoder#762]
I've received the following crashlytics after upgrading to v1.9.6:
```
Fatal Exception: java.lang.IllegalArgumentException: Unknown message type byte: 79
       at com.github.faucamp.simplertmp.packets.RtmpHeader$MessageType.valueOf(RtmpHeader.java:149)
       at com.github.faucamp.simplertmp.packets.RtmpHeader.readHeaderImpl(RtmpHeader.java:234)
       at com.github.faucamp.simplertmp.packets.RtmpHeader.readHeader(RtmpHeader.java:213)
       at com.github.faucamp.simplertmp.io.RtmpDecoder.readPacket(RtmpDecoder.java:36)
       at com.github.faucamp.simplertmp.io.RtmpConnection.handleRxPacketLoop(RtmpConnection.java:516)
       at com.github.faucamp.simplertmp.io.RtmpConnection.access$000(RtmpConnection.java:41)
       at com.github.faucamp.simplertmp.io.RtmpConnection$1.run(RtmpConnection.java:186)
       at java.lang.Thread.run(Thread.java:919)
```

Device: Galaxy S9+ (Android 10)

**Comment by pedroSG94** [comment]
Can you tell me media server used?
Did you test with other device?

**Comment by CubitSpeed** [comment]
> Can you tell me media server used?
> Did you test with other device?

I am using https://api.video/
I've only seen issue with this one device (via Crashlytics)

**Comment by pedroSG94** [comment]
This should be an error decoding packets send by server, not an expecific device error. This is strange.
Do you have any way to show me connection logs to know which packet failed?
Is it 100% reproducible? Maybe you can check google analytics to know if it is a puntual crash or you have this crash in all sesions

**Comment by CubitSpeed** [comment]
> This should be an error decoding packets send by server, not an expecific device error. This is strange.
> Do you have any way to show me connection logs to know which packet failed?
> 
> Is it 100% reproducible? Maybe, you can check google analytics to know if it is a puntual crash or you have this crash in all sesions with that device

I don't have the logs. And it seems like it has only occurred once. I was concerned since this happened right after updating the library, but maybe that was just bad luck.

If you'd like, you can close this issue. If I see more of this in the future, I will collect logs and can create  a new issues. Thank you for looking into this.

**Comment by pedroSG94** [comment]
Ok, I will let it open for now

**Comment by pedroSG94** [comment]
Closing as inactive
