### ISSUE TITLE
Parallel streaming on YT, FB and Twitch not working

### ISSUE THREAD

**Issue by jyotir1994** [pedroSG94/RootEncoder#858]
Getting this error when trying to stream on YT, FB and Twitch same time

 2021-05-12 14:29:20.981 21055-21583/**** E/AndroidRuntime: FATAL EXCEPTION: Thread-15
    Process: ****, PID: 21055
    java.lang.IllegalArgumentException: Unknown message type byte: 00
        at com.github.faucamp.simplertmp.packets.RtmpHeader$MessageType.valueOf(RtmpHeader.java:149)
        at com.github.faucamp.simplertmp.packets.RtmpHeader.readHeaderImpl(RtmpHeader.java:234)
        at com.github.faucamp.simplertmp.packets.RtmpHeader.readHeader(RtmpHeader.java:213)
        at com.github.faucamp.simplertmp.io.RtmpDecoder.readPacket(RtmpDecoder.java:36)
        at com.github.faucamp.simplertmp.io.RtmpConnection.handleRxPacketLoop(RtmpConnection.java:534)
        at com.github.faucamp.simplertmp.io.RtmpConnection.access$000(RtmpConnection.java:44)
        at com.github.faucamp.simplertmp.io.RtmpConnection$1.run(RtmpConnection.java:160)
        at java.lang.Thread.run(Thread.java:919)

**Comment by pedroSG94** [comment]
Can you share code used to stream in 3 different platforms and emulate your case?

**Comment by pedroSG94** [comment]
Closing as inactive.
