### ISSUE TITLE
Screen turns white

### ISSUE THREAD

**Issue by jyotir1994** [pedroSG94/RootEncoder#859]
When I try to stream parallelly on YT and FB screen turns white and getting this error

SurfaceView: Exception configuring surface
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_setCallback(Native Method)
        at android.media.MediaCodec.setCallback(MediaCodec.java:3377)
        at com.pedro.encoder.video.VideoEncoder.start(VideoEncoder.java:158)
        at com.pedro.encoder.BaseEncoder.start(BaseEncoder.java:25)
        at com.pedro.rtplibrary.base.Camera2Base.startEncoders(Camera2Base.java:498)
        at com.pedro.rtplibrary.base.Camera2Base.startStream(Camera2Base.java:467)
        at com.pabsa.livestream.ui.activities.LiveStreamActivity.startStream(LiveStreamActivity.kt:754)
        at com.pabsa.livestream.ui.activities.LiveStreamActivity.surfaceChanged(LiveStreamActivity.kt:643)
        at android.view.SurfaceView.updateSurface(SurfaceView.java:682)
        at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:143)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2474)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by jyotir1994** [comment]
And sometimes I'm getting this error when trying to stream on YT and FB same time-

RtmpConnection: Error
    java.net.SocketException: Socket closed
        at java.net.SocketInputStream.read(SocketInputStream.java:209)
        at java.net.SocketInputStream.read(SocketInputStream.java:144)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:248)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:267)
        at com.github.faucamp.simplertmp.packets.Handshake.readS0(Handshake.java:52)
        at com.github.faucamp.simplertmp.io.RtmpConnection.handshake(RtmpConnection.java:88)
        at com.github.faucamp.simplertmp.io.RtmpConnection.establishConnection(RtmpConnection.java:180)
        at com.github.faucamp.simplertmp.io.RtmpConnection.connect(RtmpConnection.java:153)
        at com.github.faucamp.simplertmp.DefaultRtmpPublisher.connect(DefaultRtmpPublisher.java:21)
        at net.ossrs.rtmp.SrsFlvMuxer.connect(SrsFlvMuxer.java:249)
        at net.ossrs.rtmp.SrsFlvMuxer.access$200(SrsFlvMuxer.java:53)
        at net.ossrs.rtmp.SrsFlvMuxer$2.run(SrsFlvMuxer.java:291)
        at java.lang.Thread.run(Thread.java:919)

**Comment by pedroSG94** [comment]
Can you share code used to stream in 2 different platforms and emulate your case?
Is it 100% reproducible?
