### ISSUE TITLE
Screen freezes for several seconds after stopStream is called

### ISSUE THREAD

**Issue by about-prog** [pedroSG94/RootEncoder#902]
Hello!
I have a problem. RTSP stream to wowza works great. But when I call stopStream screen freezes.
In logs "wrote packet" messages continue to appear. Then java.io.IOException: Stream closed and java.net.SocketException: Socket closed exception. And after that screen unfreeze. Here is more logs:

2021-07-03 17:25:16.413 10597-11066/com.some-site.xyz I/BaseRtpSocket: wrote packet: Video, size: 1476
2021-07-03 17:25:16.883 10597-10597/com.some-site.xyz I/TextStreamObject: finish load text
2021-07-03 17:25:16.928 10597-11066/com.some-site.xyz I/BaseRtpSocket: wrote packet: Video, size: 1476
2021-07-03 17:25:16.928 10597-11066/com.some-site.xyz I/BaseRtpSocket: wrote packet: Video, size: 1128
2021-07-03 17:25:16.928 10597-11066/com.some-site.xyz I/BaseRtpSocket: wrote packet: Video, size: 1476
2021-07-03 17:25:16.929 10597-11066/com.some-site.xyz I/chatty: uid=10256(com.some-site.xyz) RtspSender identical 2 lines
2021-07-03 17:25:16.929 10597-11066/com.some-site.xyz I/BaseRtpSocket: wrote packet: Video, size: 1476
2021-07-03 17:25:16.929 10597-11066/com.some-site.xyz I/BaseRtpSocket: wrote packet: Video, size: 125
2021-07-03 17:25:16.929 10597-11066/com.some-site.xyz I/BaseRtpSocket: wrote packet: Audio, size: 719
2021-07-03 17:25:16.929 10597-11066/com.some-site.xyz I/BaseRtpSocket: wrote packet: Video, size: 1476
2021-07-03 17:25:16.929 10597-11066/com.some-site.xyz I/chatty: uid=10256(com.some-site.xyz) RtspSender identical 1 line
2021-07-03 17:25:16.929 10597-11066/com.some-site.xyz I/BaseRtpSocket: wrote packet: Video, size: 1476
2021-07-03 17:25:17.396 10597-11066/com.some-site.xyz I/BaseRtpSocket: wrote packet: Video, size: 1476
2021-07-03 17:25:17.396 10597-11066/com.some-site.xyz I/BaseSenderReport: wrote report: Video, packets: 403, octet: 542006
2021-07-03 17:25:17.397 10597-11066/com.some-site.xyz I/BaseRtpSocket: wrote packet: Video, size: 1476
2021-07-03 17:25:17.397 10597-11066/com.some-site.xyz I/BaseRtpSocket: wrote packet: Video, size: 538
2021-07-03 17:25:17.397 10597-11066/com.some-site.xyz I/BaseRtpSocket: wrote packet: Audio, size: 719
2021-07-03 17:25:17.397 10597-11066/com.some-site.xyz I/BaseRtpSocket: wrote packet: Video, size: 1476
2021-07-03 17:25:17.397 10597-11066/com.some-site.xyz I/chatty: uid=10256(com.some-site.xyz) RtspSender identical 1 line
2021-07-03 17:25:17.397 10597-11066/com.some-site.xyz I/BaseRtpSocket: wrote packet: Video, size: 1476
2021-07-03 17:25:17.397 10597-11066/com.some-site.xyz I/BaseRtpSocket: wrote packet: Video, size: 445
2021-07-03 17:25:17.398 10597-11066/com.some-site.xyz I/BaseRtpSocket: wrote packet: Audio, size: 719
2021-07-03 17:25:17.398 10597-11066/com.some-site.xyz I/BaseRtpSocket: wrote packet: Video, size: 1476
2021-07-03 17:25:17.443 10597-10597/com.some-site.xyz D/ViewRootImpl@99f04cd[CameraActivity]: ViewPostIme pointer 0
2021-07-03 17:25:17.510 10597-10597/com.some-site.xyz D/ViewRootImpl@99f04cd[CameraActivity]: ViewPostIme pointer 1
2021-07-03 17:25:17.910 10597-11066/com.some-site.xyz I/BaseRtpSocket: wrote packet: Video, size: 1476
2021-07-03 17:25:17.910 10597-11066/com.some-site.xyz I/BaseSenderReport: wrote report: Video, packets: 1, octet: 1472
2021-07-03 17:25:19.429 10597-10980/com.some-site.xyz I/MediaCodec: setCodecState state : 0
2021-07-03 17:25:19.914 10597-11051/com.some-site.xyz E/CommandsManager: read error
    java.io.IOException: Stream closed
        at java.io.BufferedReader.ensureOpen(BufferedReader.java:123)
        at java.io.BufferedReader.readLine(BufferedReader.java:328)
        at java.io.BufferedReader.readLine(BufferedReader.java:400)
        at com.pedro.rtsp.rtsp.commands.CommandsManager.getResponse(CommandsManager.kt:235)
        at com.pedro.rtsp.rtsp.commands.CommandsManager.getResponse$default(CommandsManager.kt:230)
        at com.pedro.rtsp.rtsp.RtspClient.handleServerCommands(RtspClient.kt:262)
        at com.pedro.rtsp.rtsp.RtspClient.connect$lambda-2$lambda-1(RtspClient.kt:244)
        at com.pedro.rtsp.rtsp.RtspClient.lambda$lzkncoUC9PwRQWcS00cbY5dRDDA(Unknown Source:0)
        at com.pedro.rtsp.rtsp.-$$Lambda$RtspClient$lzkncoUC9PwRQWcS00cbY5dRDDA.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2021-07-03 17:25:19.917 10597-11106/com.some-site.xyz I/CommandsManager: TEARDOWN rtsp://xl1.some-site.com:1935/rtmp/watcher59 RTSP/1.0
    CSeq: 6
    User-Agent: com.pedro.rtsp 2.0.5
    Session: 1709046303
2021-07-03 17:25:19.918 10597-11106/com.some-site.xyz E/RtspClient: disconnect error
    java.net.SocketException: Socket closed
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:124)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:161)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at java.io.BufferedWriter.flush(BufferedWriter.java:254)
        at com.pedro.rtsp.rtsp.RtspClient.disconnect$lambda-6$lambda-5(RtspClient.kt:295)
        at com.pedro.rtsp.rtsp.RtspClient.lambda$ChMVPVfTTfK0WJ-T9hqF_yzQriw(Unknown Source:0)
        at com.pedro.rtsp.rtsp.-$$Lambda$RtspClient$ChMVPVfTTfK0WJ-T9hqF_yzQriw.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2021-07-03 17:25:19.954 10597-10597/com.some-site.xyz I/MicrophoneManager: Microphone stopped
2021-07-03 17:25:19.955 10597-10597/com.some-site.xyz I/SurfaceManager: GL released
2021-07-03 17:25:19.956 10597-10597/com.some-site.xyz I/SurfaceManager: GL released
2021-07-03 17:25:19.957 10597-10597/com.some-site.xyz I/SurfaceManager: GL initialized
2021-07-03 17:25:19.957 10597-10597/com.some-site.xyz I/VideoEncoder: stopped
2021-07-03 17:25:19.958 10597-10980/com.some-site.xyz I/ACodec: [OMX.Exynos.AVC.Encoder] signalFlush
2021-07-03 17:25:19.958 10597-10981/com.some-site.xyz I/ACodec: [OMX.Exynos.AVC.Encoder] ExecutingState flushing now (codec owns 0/5 input, 4/4 output).
2021-07-03 17:25:19.958 10597-10981/com.some-site.xyz I/ACodec: [OMX.Exynos.AVC.Encoder] Now Flushing
2021-07-03 17:25:19.961 10597-10981/com.some-site.xyz I/ACodec: [OMX.Exynos.AVC.Encoder] FlushingState onOMXEvent(0,1,0)
2021-07-03 17:25:19.961 10597-10981/com.some-site.xyz I/ACodec: [OMX.Exynos.AVC.Encoder] FlushingState onOMXEvent(0,1,1)
2021-07-03 17:25:19.961 10597-10981/com.some-site.xyz I/ACodec: [OMX.Exynos.AVC.Encoder] Now Executing
2021-07-03 17:25:19.962 10597-10981/com.some-site.xyz I/ACodec: [OMX.Exynos.AVC.Encoder] Now Executing->Idle
2021-07-03 17:25:19.967 10597-10981/com.some-site.xyz I/ACodec: [OMX.Exynos.AVC.Encoder] Now Idle->Loaded
2021-07-03 17:25:19.969 10597-10981/com.some-site.xyz I/ACodec: [OMX.Exynos.AVC.Encoder] Now Loaded
2021-07-03 17:25:19.969 10597-10981/com.some-site.xyz I/ACodec:  [OMX.Exynos.AVC.Encoder] Now kWhatShutdownCompleted event : 8553
2021-07-03 17:25:19.971 10597-10981/com.some-site.xyz I/ACodec:  [OMX.Exynos.AVC.Encoder] Now uninitialized
2021-07-03 17:25:19.971 10597-10981/com.some-site.xyz I/ACodec:  [] Now kWhatShutdownCompleted event : 8553
2021-07-03 17:25:19.973 10597-10980/com.some-site.xyz I/MediaCodec: Codec shutdown complete
2021-07-03 17:25:19.976 10597-10597/com.some-site.xyz I/AudioEncoder: stopped
2021-07-03 17:25:19.976 10597-10988/com.some-site.xyz I/ACodec: [OMX.SEC.naac.enc] signalFlush
2021-07-03 17:25:19.976 10597-10988/com.some-site.xyz I/ACodec: [OMX.SEC.naac.enc] ExecutingState flushing now (codec owns 0/4 input, 3/5 output).
2021-07-03 17:25:19.977 10597-10988/com.some-site.xyz I/ACodec: [OMX.SEC.naac.enc] Now Flushing
2021-07-03 17:25:19.977 10597-10988/com.some-site.xyz I/ACodec: [OMX.SEC.naac.enc] FlushingState onOMXEvent(0,1,0)
2021-07-03 17:25:19.977 10597-10988/com.some-site.xyz I/ACodec: [OMX.SEC.naac.enc] FlushingState onOMXEvent(0,1,1)
2021-07-03 17:25:19.977 10597-10988/com.some-site.xyz I/ACodec: [OMX.SEC.naac.enc] Now Executing
2021-07-03 17:25:19.978 10597-10988/com.some-site.xyz I/ACodec: [OMX.SEC.naac.enc] Now Executing->Idle
2021-07-03 17:25:19.980 10597-10988/com.some-site.xyz I/ACodec: [OMX.SEC.naac.enc] Now Idle->Loaded
2021-07-03 17:25:19.981 10597-10988/com.some-site.xyz I/ACodec: [OMX.SEC.naac.enc] Now Loaded
2021-07-03 17:25:19.981 10597-10988/com.some-site.xyz I/ACodec:  [OMX.SEC.naac.enc] Now kWhatShutdownCompleted event : 8553
2021-07-03 17:25:19.982 10597-10988/com.some-site.xyz I/ACodec:  [OMX.SEC.naac.enc] Now uninitialized
2021-07-03 17:25:19.983 10597-10988/com.some-site.xyz I/ACodec:  [] Now kWhatShutdownCompleted event : 8553
2021-07-03 17:25:19.983 10597-10988/com.some-site.xyz I/MediaCodec: Codec shutdown complete
2021-07-03 17:25:19.989 10597-10597/com.some-site.xyz I/Choreographer: Skipped 147 frames!  The application may be doing too much work on its main thread.
2021-07-03 17:25:20.004 10597-10597/com.some-site.xyz I/TextStreamObject: finish load text
2021-07-03 17:25:20.006 10597-10709/com.some-site.xyz I/OpenGLRenderer: Davey! duration=2482ms; Flags=0, IntendedVsync=786564260697595, Vsync=786566710697497, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=786566727418326, AnimationStart=786566727460865, PerformTraversalsStart=786566727462480, DrawStart=786566734238057, SyncQueued=786566736635403, SyncStart=786566736716326, IssueDrawCommandsStart=786566736846172, SwapBuffers=786566742648211, FrameCompleted=786566743598480, DequeueBufferDuration=505000, QueueBufferDuration=500000, 
2021-07-03 17:25:20.702 10597-10597/com.some-site.xyz I/chromium: [INFO:CONSOLE(134)] "pong", source: https://some-site.com/static/js/v2/app/rtc_android.js?618 (134)
2021-07-03 17:25:21.006 10597-10597/com.some-site.xyz I/TextStreamObject: finish load text
2021-07-03 17:25:22.007 10597-10597/com.some-site.xyz I/TextStreamObject: finish load text
2021-07-03 17:25:23.010 10597-10597/com.some-site.xyz I/TextStreamObject: finish load text
2021-07-03 17:25:24.012 10597-10597/com.some-site.xyz I/TextStreamObject: finish load text
2021-07-03 17:25:24.284 10597-10597/com.some-site.xyz D/InputMethodManager: prepareNavigationBarInfo() DecorView@321fae0[CameraActivity]
2021-07-03 17:25:24.284 10597-10597/com.some-site.xyz D/InputMethodManager: getNavigationBarColor() -855310
2021-07-03 17:25:24.284 10597-10597/com.some-site.xyz D/InputMethodManager: startInputInner - Id : 0
2021-07-03 17:25:24.284 10597-10597/com.some-site.xyz I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2021-07-03 17:25:24.286 10597-10597/com.some-site.xyz D/InputTransport: Input channel constructed: fd=149
2021-07-03 17:25:24.286 10597-10597/com.some-site.xyz D/InputTransport: Input channel destroyed: fd=53
2021-07-03 17:25:24.647 10597-10597/com.some-site.xyz I/xyz: CameraActivity: onPause
2021-07-03 17:25:24.647 10597-10597/com.some-site.xyz I/xyz: CameraActivity: onPause finished
2021-07-03 17:25:24.673 10597-10597/com.some-site.xyz D/ViewRootImpl@99f04cd[CameraActivity]: setWindowStopped(true) old=false
2021-07-03 17:25:24.680 10597-10597/com.some-site.xyz D/SurfaceView: windowStopped(true) false com.pedro.rtplibrary.view.OpenGlView{fb9b182 V.E...... ........ 0,0-720,1336 #7f09017e app:id/surfaceView} of ViewRootImpl@99f04cd[CameraActivity]
2021-07-03 17:25:24.681 10597-10597/com.some-site.xyz D/SurfaceView: show() Surface(name=SurfaceView - com.some-site.xyz/com.some-site.xyz.CameraActivity@fb9b182@0[10597])/@0xac7f1fc com.pedro.rtplibrary.view.OpenGlView{fb9b182 V.E...... ........ 0,0-720,1336 #7f09017e app:id/surfaceView}
2021-07-03 17:25:24.684 10597-10597/com.some-site.xyz D/SurfaceView: surfaceDestroyed callback.size 2 #1 com.pedro.rtplibrary.view.OpenGlView{fb9b182 V.E...... ........ 0,0-720,1336 #7f09017e app:id/surfaceView}
2021-07-03 17:25:24.786 10597-10597/com.some-site.xyz I/SurfaceManager: GL released
2021-07-03 17:25:24.786 10597-10597/com.some-site.xyz E/SurfaceManager: GL already released
2021-07-03 17:25:24.790 10597-10597/com.some-site.xyz I/SurfaceManager: GL released
2021-07-03 17:25:24.791 10597-10597/com.some-site.xyz E/SurfaceManager: GL already released
2021-07-03 17:25:24.791 10597-10597/com.some-site.xyz I/chatty: uid=10256(com.some-site.xyz) identical 1 line
2021-07-03 17:25:24.791 10597-10597/com.some-site.xyz E/SurfaceManager: GL already released
2021-07-03 17:25:24.795 10597-10995/com.some-site.xyz E/SurfaceManager: GL already released
2021-07-03 17:25:24.795 10597-10995/com.some-site.xyz I/chatty: uid=10256(com.some-site.xyz) identical 1 line
2021-07-03 17:25:24.795 10597-10995/com.some-site.xyz E/SurfaceManager: GL already released
2021-07-03 17:25:24.799 10597-10995/com.some-site.xyz W/mali_winsys: native_window_api_disconnect failed: -19
2021-07-03 17:25:24.834 10597-10621/com.some-site.xyz E/BufferQueueProducer: [SurfaceTexture-1-10597-1] dequeueBuffer: BufferQueue has been abandoned
2021-07-03 17:25:24.834 10597-10621/com.some-site.xyz E/BufferQueueProducer: [SurfaceTexture-1-10597-1] dequeueBuffer: BufferQueue has been abandoned
2021-07-03 17:25:24.844 10597-11110/com.some-site.xyz E/BufferQueueProducer: [SurfaceTexture-1-10597-1] queueBuffer: BufferQueue has been abandoned
2021-07-03 17:25:24.845 10597-10621/com.some-site.xyz E/BufferQueueProducer: [SurfaceTexture-1-10597-1] dequeueBuffer: BufferQueue has been abandoned
2021-07-03 17:25:24.846 10597-10621/com.some-site.xyz E/BufferQueueProducer: [SurfaceTexture-1-10597-1] dequeueBuffer: BufferQueue has been abandoned
2021-07-03 17:25:24.847 10597-11110/com.some-site.xyz E/BufferQueueProducer: [SurfaceTexture-1-10597-1] cancelBuffer: BufferQueue has been abandoned

**Comment by pedroSG94** [comment]
Can you tell me device model and API?
Can you reproduce this error in multiple devices?

**Comment by about-prog** [comment]
Have tested. The problem is with Samsung Galaxies. Tested with Galaxy 8 and Galaxy 10. Also, the problem seems to appear on Galaxy s21.

Can reproduce on your app example. I have used OpenGL RTSP. After I stream 10-20 seconds and then try to stop the stream, the screen freezes for some time (this time interval differs from time to time),

**Comment by pedroSG94** [comment]
> Can the problem be with the server configuration? We use latest Wowza

I don't think, but you can test with other server to discard it:
https://github.com/EasyDarwin/EasyDarwin

**Comment by pedroSG94** [comment]
Compile this branch and show me logs to know the point where you are getting this delay problem:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/stoptime

**Comment by pedroSG94** [comment]
Closing as inactive
