### ISSUE TITLE
Multiple Streams crashes on stop(): Using v1.8.2

### ISSUE THREAD

**Issue by aryanA101a** [pedroSG94/RootEncoder#912]
E/AndroidRuntime(29016): FATAL EXCEPTION: Thread-273
E/AndroidRuntime(29016): Process: com.example.degpeg_app, PID: 29016
E/AndroidRuntime(29016): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.github.faucamp.simplertmp.io.RtmpSessionInfo.addInvokedCommand(int, java.lang.String)' on a null object reference
E/AndroidRuntime(29016): 	at com.github.faucamp.simplertmp.io.RtmpConnection.sendRtmpPacket(RtmpConnection.java:471)
E/AndroidRuntime(29016): 	at com.github.faucamp.simplertmp.io.RtmpConnection.closeStream(RtmpConnection.java:360)
E/AndroidRuntime(29016): 	at com.github.faucamp.simplertmp.io.RtmpConnection.close(RtmpConnection.java:345)
E/AndroidRuntime(29016): 	at com.github.faucamp.simplertmp.DefaultRtmpPublisher.close(DefaultRtmpPublisher.java:31)
E/AndroidRuntime(29016): 	at net.ossrs.rtmp.SrsFlvMuxer.disconnect(SrsFlvMuxer.java:191)
E/AndroidRuntime(29016): 	at net.ossrs.rtmp.SrsFlvMuxer.access$1000(SrsFlvMuxer.java:53)
E/AndroidRuntime(29016): 	at net.ossrs.rtmp.SrsFlvMuxer$3.run(SrsFlvMuxer.java:334)
E/AndroidRuntime(29016): 	at java.lang.Thread.run(Thread.java:764)
2
D/RtmpConnection(29016): wrote packet: RTMP Command (command: closeStream, transaction ID: 0), size: 24
2
I/Process (29016): Sending signal. PID: 29016 SIG: 9

**Comment by pedroSG94** [comment]
Hello,

Actally you are using a old library version and I can't give you support for it. Please update library and check if it is working for you because rtmp module had a big change

**Comment by aryanA101a** [comment]
Hi,
Now that I am using v2.0.3, after pressing the stop button the app crashes

Log:
```
I/flutter (26647): StreamStatistics{cacheSize: 60, sentAudioFrames: 14494, sentVideoFrames: 14162, droppedAudioFrames: null, droppedVideoFrames: 9001, isAudioMuted: false, bitrate: 1228800, width: 480, height: 720}
I/flutter (26647): StreamStatistics{cacheSize: 30, sentAudioFrames: 14501, sentVideoFrames: 14168, droppedAudioFrames: null, droppedVideoFrames: 9001, isAudioMuted: false, bitrate: 1228800, width: 480, height: 720}
I/flutter (26647): StreamStatistics{cacheSize: 60, sentAudioFrames: 14501, sentVideoFrames: 14168, droppedAudioFrames: null, droppedVideoFrames: 9024, isAudioMuted: false, bitrate: 1228800, width: 480, height: 720}
I/flutter (26647): Stop video streaming call
E/flutter (26647): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: CameraException(No camera is streaming images, stopImageStream was called when no camera is streaming images.)     
E/flutter (26647): #0      CameraController.getStreamStatistics (package:degpeg/camera.dart:555)
E/flutter (26647): #1      _LivePreviewState.startVideoStreaming.<anonymous closure> (package:degpeg_app/Screens/live_preview.dart:984)
E/flutter (26647): #2      _LivePreviewState.startVideoStreaming.<anonymous closure> (package:degpeg_app/Screens/live_preview.dart:983)
E/flutter (26647): #3      _rootRunUnary (dart:async/zone.dart:1362)
E/flutter (26647): #4      _CustomZone.runUnary (dart:async/zone.dart:1265)
E/flutter (26647): #5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170)
E/flutter (26647): #6      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1207)
E/flutter (26647): #7      _rootRunUnary (dart:async/zone.dart:1370)
E/flutter (26647): #8      _CustomZone.runUnary (dart:async/zone.dart:1265)
E/flutter (26647): #9      _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1191)
E/flutter (26647): #10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395)
E/flutter (26647): #11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426)
E/flutter (26647): #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
E/flutter (26647):
E/AndroidRuntime(26647): FATAL EXCEPTION: Thread-664
E/AndroidRuntime(26647): Process: com.example.degpeg_app, PID: 26647
E/AndroidRuntime(26647): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Looper.quit()' on a null object reference
E/AndroidRuntime(26647):        at c.d.a.a.u(Unknown Source:53)
E/AndroidRuntime(26647):        at c.d.a.a.t(Unknown Source:1)
E/AndroidRuntime(26647):        at c.a.a.i.d0(Unknown Source:36)
E/AndroidRuntime(26647):        at c.a.a.a.f(Unknown Source:7)
E/AndroidRuntime(26647):        at c.a.a.i.f(Unknown Source:2)
E/AndroidRuntime(26647):        at i.a.a.e.v(Unknown Source:18)
E/AndroidRuntime(26647):        at i.a.a.e.t(Unknown Source:0)
E/AndroidRuntime(26647):        at i.a.a.e$c.run(Unknown Source:4)
E/AndroidRuntime(26647):        at java.lang.Thread.run(Thread.java:764)
E/flutter (26647): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: CameraException(No camera is streaming images, stopImageStream was called when no camera is streaming images.)     
E/flutter (26647): #0      CameraController.getStreamStatistics (package:degpeg/camera.dart:555)
E/flutter (26647): #1      _LivePreviewState.startVideoStreaming.<anonymous closure> (package:degpeg_app/Screens/live_preview.dart:984)
E/flutter (26647): #2      _LivePreviewState.startVideoStreaming.<anonymous closure> (package:degpeg_app/Screens/live_preview.dart:983)
E/flutter (26647): #3      _rootRunUnary (dart:async/zone.dart:1362)
E/flutter (26647): #4      _CustomZone.runUnary (dart:async/zone.dart:1265)
E/flutter (26647): #5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170)
E/flutter (26647): #6      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1207)
E/flutter (26647): #7      _rootRunUnary (dart:async/zone.dart:1370)
E/flutter (26647): #8      _CustomZone.runUnary (dart:async/zone.dart:1265)
E/flutter (26647): #9      _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1191)
E/flutter (26647): #10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395)
E/flutter (26647): #11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426)
E/flutter (26647): #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
E/flutter (26647):
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
I/flutter (26647): Event {errorDescription: Disconnected, eventType: rtmp_stopped}
```

**Comment by pedroSG94** [comment]
Please, Compile last version (2.0.5) and share my a logcat without encryptation to know crash line
