### ISSUE TITLE
Update video parameters

### ISSUE THREAD

**Issue by ThibaultBee** [pedroSG94/RootEncoder#954]
Hi Pedro,

I am working with RtmpCamera2 with an OpenGlView.
I am trying to update video parameters with `prepareVideo(int width, int height, int fps, int bitrate, int rotation)` and a new configuration.
When I am try to update video parameters preview is running and streaming is off.
I tried with calling;
```
stopPreview
prepareVideo
startPreview
```
Unfortunately the following crash happens:
```
2021-10-12 10:38:52.132 32398-32398/video.api.livestream.app I/AudioEncoder: 1 encoders found
2021-10-12 10:38:52.132 32398-32398/video.api.livestream.app I/AudioEncoder: Encoder OMX.google.aac.encoder
2021-10-12 10:38:52.132 32398-32398/video.api.livestream.app I/AudioEncoder: Encoder selected OMX.google.aac.encoder
2021-10-12 10:38:52.136 32398-32666/video.api.livestream.app I/OMXClient: Using client-side OMX mux.
2021-10-12 10:38:52.138 32398-32666/video.api.livestream.app E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
2021-10-12 10:38:52.140 32398-32398/video.api.livestream.app I/AudioEncoder: prepared
2021-10-12 10:38:52.140 32398-32398/video.api.livestream.app I/VideoEncoder: started
2021-10-12 10:38:52.142 32398-32659/video.api.livestream.app I/MediaCodec: MediaCodec will operate in async mode
2021-10-12 10:38:52.155 32398-32398/video.api.livestream.app I/AudioEncoder: started
2021-10-12 10:38:52.156 32398-32666/video.api.livestream.app I/MediaCodec: MediaCodec will operate in async mode
2021-10-12 10:38:52.158 32398-32398/video.api.livestream.app I/OpenGlViewBase: Thread started.
2021-10-12 10:38:52.160 32398-32671/video.api.livestream.app E/SurfaceManager: GL already released
2021-10-12 10:38:52.164 32398-32671/video.api.livestream.app E/libEGL: eglCreateWindowSurface: native_window_api_connect (win=0x9d405108) failed (0xffffffea) (already connected to another API?)
2021-10-12 10:38:52.164 32398-32671/video.api.livestream.app E/libEGL: eglCreateWindowSurface:456 error 3003 (EGL_BAD_ALLOC)
2021-10-12 10:38:52.165 32398-32671/video.api.livestream.app E/AndroidRuntime: FATAL EXCEPTION: glThread
    Process: video.api.livestream.app, PID: 32398
    java.lang.RuntimeException: eglCreateWindowSurface. EGL error: 12291
        at com.pedro.encoder.utils.gl.GlUtil.checkEglError(GlUtil.java:149)
        at com.pedro.encoder.input.gl.SurfaceManager.eglSetup(SurfaceManager.java:155)
        at com.pedro.encoder.input.gl.SurfaceManager.eglSetup(SurfaceManager.java:173)
        at com.pedro.rtplibrary.view.OpenGlView.run(OpenGlView.java:175)
        at java.lang.Thread.run(Thread.java:818)
2021-10-12 10:38:58.147 32398-32671/video.api.livestream.app I/Process: Sending signal. PID: 32398 SIG: 9
```

I tried with just:
`prepareVideo()`
but the camera preview is stuck.

What is the correct way to use `prepareVideo()`?

**Comment by ThibaultBee** [comment]
I want to adapt both preview and stream resolution (and fps, bitrate,...).
I guess stream will be update later as I call prepareVideo() and prepareAudio() in a startStream method.
First, I want to set the preview resolution, so as you said, I tried to perform:
`
            rtmpCamera2.stopPreview()
            rtmpCamera2.startPreview(rtmpCamera2.cameraFacing,1280, 720)
 `
I still get the exception:
`
2021-10-13 14:04:14.178 10013-10149/video.api.livestream.app E/SurfaceManager: GL already released
2021-10-13 14:04:14.182 10013-10149/video.api.livestream.app E/libEGL: eglCreateWindowSurface: native_window_api_connect (win=0xaebfb908) failed (0xffffffea) (already connected to another API?)
2021-10-13 14:04:14.183 10013-10149/video.api.livestream.app E/libEGL: eglCreateWindowSurface:456 error 3003 (EGL_BAD_ALLOC)
2021-10-13 14:04:14.183 10013-10149/video.api.livestream.app E/AndroidRuntime: FATAL EXCEPTION: glThread
    Process: video.api.livestream.app, PID: 10013
    java.lang.RuntimeException: eglCreateWindowSurface. EGL error: 12291
        at com.pedro.encoder.utils.gl.GlUtil.checkEglError(GlUtil.java:149)
        at com.pedro.encoder.input.gl.SurfaceManager.eglSetup(SurfaceManager.java:155)
        at com.pedro.encoder.input.gl.SurfaceManager.eglSetup(SurfaceManager.java:173)
        at com.pedro.rtplibrary.view.OpenGlView.run(OpenGlView.java:175)
        at java.lang.Thread.run(Thread.java:818)
`
I am still missing something...

**Comment by pedroSG94** [comment]
Can you share me code used to reproduce the error?

**Comment by ThibaultBee** [comment]
* The exception also happens with RtmpCamera1
* If I call rtmpCamera1.prepareVideo(1280, 720, 1200 * 1024) instead of rtmpCamera1.prepareVideo() in your app's onClick, I still get the exception

**Comment by pedroSG94** [comment]
You can do it using this method:
```java
    rtmpCamera2.setLogs(false);
```
